/* Infrastructure project financials, auto-generated from the reference-page models.
   Source of truth for the M&A module asset picker. Regenerate with the throwaway
   harvester if the reference models change. Do not hand-edit. */
window.MA_ASSETS = {
 "generated": "2026-06-19",
 "note": "Per-asset base-case financials harvested from each reference page model. EBITDA is year-1, native currency (millions). ev is the implied entry enterprise value (the reference model invested capital); entry is the implied entry EV/EBITDA (clamped to a sane band, else the terminal multiple); exit is the modelled terminal EV/EBITDA. lev/growth/hold/rd are the modelled assumptions; uirr/lirr/moic are the reference returns.",
 "classOrder": [
  "Energy & Utilities",
  "Transport",
  "Digital Infrastructure",
  "Social Infrastructure",
  "Energy Transition",
  "Environmental & Waste"
 ],
 "sectors": [
  {
   "cls": "Energy & Utilities",
   "name": "Electricity transmission",
   "url": "electricity-transmission.html",
   "assets": [
    {
     "key": "nationalgrid",
     "name": "National Grid ET",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 1768,
     "ev": 17000,
     "entry": 9.5,
     "exit": 10,
     "lev": 6,
     "growth": 4,
     "hold": 25,
     "rd": 5,
     "uirr": "6.2%",
     "lirr": "7.7%",
     "moic": "6.45×"
    },
    {
     "key": "itc",
     "name": "ITC Holdings",
     "geo": "US Midwest",
     "cur": "US$",
     "ebitda": 1080,
     "ev": 10000,
     "entry": 9.5,
     "exit": 10,
     "lev": 6,
     "growth": 5,
     "hold": 25,
     "rd": 5,
     "uirr": "7.9%",
     "lirr": "10.7%",
     "moic": "10.37×"
    },
    {
     "key": "cteep",
     "name": "ISA CTEEP",
     "geo": "Brazil",
     "cur": "R$",
     "ebitda": 2618,
     "ev": 22000,
     "entry": 8.5,
     "exit": 9,
     "lev": 5,
     "growth": 5,
     "hold": 25,
     "rd": 10,
     "uirr": "7.3%",
     "lirr": "7.6%",
     "moic": "7.83×"
    },
    {
     "key": "transgrid",
     "name": "TransGrid",
     "geo": "New South Wales, Australia",
     "cur": "A$",
     "ebitda": 784,
     "ev": 10300,
     "entry": 13,
     "exit": 11,
     "lev": 6,
     "growth": 7,
     "hold": 30,
     "rd": 5,
     "uirr": "7.0%",
     "lirr": "7.9%",
     "moic": "10.65×"
    },
    {
     "key": "saudi",
     "name": "National Grid SA",
     "geo": "Saudi Arabia",
     "cur": "$",
     "ebitda": 9270,
     "ev": 90000,
     "entry": 9.5,
     "exit": 9.5,
     "lev": 5,
     "growth": 6,
     "hold": 25,
     "rd": 4.5,
     "uirr": "8.8%",
     "lirr": "10.5%",
     "moic": "9.65×"
    },
    {
     "key": "stategrid",
     "name": "State Grid (UHV)",
     "geo": "China",
     "cur": "$",
     "ebitda": 73600,
     "ev": 800000,
     "entry": 11,
     "exit": 11,
     "lev": 4,
     "growth": 5,
     "hold": 25,
     "rd": 4,
     "uirr": "7.0%",
     "lirr": "8.0%",
     "moic": "5.84×"
    }
   ]
  },
  {
   "cls": "Energy & Utilities",
   "name": "Electricity distribution",
   "url": "electricity-distribution.html",
   "assets": [
    {
     "key": "ukpn",
     "name": "UK Power Networks",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 884,
     "ev": 8500,
     "entry": 9.5,
     "exit": 10,
     "lev": 6,
     "growth": 5,
     "hold": 25,
     "rd": 5,
     "uirr": "6.0%",
     "lirr": "7.2%",
     "moic": "7.18×"
    },
    {
     "key": "coned",
     "name": "Con Edison",
     "geo": "New York City, USA",
     "cur": "US$",
     "ebitda": 2650,
     "ev": 25000,
     "entry": 9.5,
     "exit": 11,
     "lev": 5,
     "growth": 4,
     "hold": 25,
     "rd": 5,
     "uirr": "7.2%",
     "lirr": "8.9%",
     "moic": "6.79×"
    },
    {
     "key": "enelbr",
     "name": "Enel Distribución Brasil",
     "geo": "São Paulo, Brazil",
     "cur": "R$",
     "ebitda": 1936,
     "ev": 16000,
     "entry": 8.5,
     "exit": 9,
     "lev": 4,
     "growth": 5,
     "hold": 25,
     "rd": 9,
     "uirr": "7.3%",
     "lirr": "7.7%",
     "moic": "6.82×"
    },
    {
     "key": "ausgrid",
     "name": "Ausgrid",
     "geo": "New South Wales, Australia",
     "cur": "A$",
     "ebitda": 1666,
     "ev": 20000,
     "entry": 12,
     "exit": 11,
     "lev": 6,
     "growth": 4,
     "hold": 30,
     "rd": 5,
     "uirr": "5.7%",
     "lirr": "6.6%",
     "moic": "6.07×"
    },
    {
     "key": "dewa",
     "name": "DEWA",
     "geo": "Dubai, UAE",
     "cur": "$",
     "ebitda": 9720,
     "ev": 90000,
     "entry": 9.5,
     "exit": 10,
     "lev": 5,
     "growth": 4,
     "hold": 25,
     "rd": 4.5,
     "uirr": "8.3%",
     "lirr": "10.1%",
     "moic": "7.61×"
    },
    {
     "key": "csg",
     "name": "China Southern Power Grid",
     "geo": "Guangdong, China",
     "cur": "$",
     "ebitda": 55200,
     "ev": 600000,
     "entry": 11,
     "exit": 11,
     "lev": 4,
     "growth": 5,
     "hold": 25,
     "rd": 4,
     "uirr": "7.1%",
     "lirr": "8.1%",
     "moic": "5.91×"
    }
   ]
  },
  {
   "cls": "Energy & Utilities",
   "name": "Last-mile electricity",
   "url": "last-mile-electricity.html",
   "assets": [
    {
     "key": "gtc",
     "name": "GTC",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 21.9,
     "ev": 330,
     "entry": 15,
     "exit": 17,
     "lev": 6,
     "growth": 4,
     "hold": 25,
     "rd": 5.5,
     "uirr": "8.0%",
     "lirr": "9.1%",
     "moic": "6.22×"
    },
    {
     "key": "fpl",
     "name": "Florida Power & Light",
     "geo": "Florida, USA",
     "cur": "US$",
     "ebitda": 1326,
     "ev": 18000,
     "entry": 13.5,
     "exit": 12,
     "lev": 5,
     "growth": 4,
     "hold": 25,
     "rd": 5,
     "uirr": "5.7%",
     "lirr": "6.3%",
     "moic": "3.98×"
    },
    {
     "key": "equatorial",
     "name": "Equatorial Energia",
     "geo": "North & North-East Brazil",
     "cur": "R$",
     "ebitda": 2640,
     "ev": 20000,
     "entry": 7.5,
     "exit": 9,
     "lev": 4,
     "growth": 4,
     "hold": 15,
     "rd": 9,
     "uirr": "8.5%",
     "lirr": "10.0%",
     "moic": "4.00×"
    },
    {
     "key": "altogether",
     "name": "Altogether Group",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 11.4,
     "ev": 135,
     "entry": 12,
     "exit": 13,
     "lev": 5,
     "growth": 6,
     "hold": 20,
     "rd": 6,
     "uirr": "8.2%",
     "lirr": "9.5%",
     "moic": "5.85×"
    },
    {
     "key": "enowa",
     "name": "ENOWA · NEOM",
     "geo": "Saudi Arabia",
     "cur": "$",
     "ebitda": 85.3,
     "ev": 6496,
     "entry": 12,
     "exit": 12,
     "lev": 5,
     "growth": 10,
     "hold": 30,
     "rd": 4.5,
     "uirr": "5.2%",
     "lirr": "5.2%",
     "moic": "3.87×"
    },
    {
     "key": "stategrid",
     "name": "State Grid",
     "geo": "Eastern China",
     "cur": "$",
     "ebitda": 4480,
     "ev": 80000,
     "entry": 18,
     "exit": 11,
     "lev": 4,
     "growth": 6,
     "hold": 25,
     "rd": 4,
     "uirr": "4.2%",
     "lirr": "4.4%",
     "moic": "3.04×"
    }
   ]
  },
  {
   "cls": "Energy & Utilities",
   "name": "Electricity interconnectors",
   "url": "electricity-interconnectors.html",
   "assets": [
    {
     "key": "celtic",
     "name": "Celtic Interconnector",
     "geo": "Ireland ⇄ France",
     "cur": "€",
     "ebitda": 75.3,
     "ev": 1086,
     "entry": 14.5,
     "exit": 14,
     "lev": 6,
     "growth": 1,
     "hold": 15,
     "rd": 5,
     "uirr": "5.7%",
     "lirr": "6.7%",
     "moic": "2.23×"
    },
    {
     "key": "chpe",
     "name": "Champlain Hudson Power Express",
     "geo": "Québec ⇄ New York",
     "cur": "US$",
     "ebitda": 501,
     "ev": 6000,
     "entry": 12,
     "exit": 12,
     "lev": 8,
     "growth": 2,
     "hold": 25,
     "rd": 5,
     "uirr": "7.9%",
     "lirr": "11.4%",
     "moic": "7.33×"
    },
    {
     "key": "marinus",
     "name": "Marinus Link",
     "geo": "Tasmania ⇄ Victoria",
     "cur": "A$",
     "ebitda": 244,
     "ev": 3450,
     "entry": 14,
     "exit": 14,
     "lev": 7,
     "growth": 2.5,
     "hold": 25,
     "rd": 5.5,
     "uirr": "7.1%",
     "lirr": "8.6%",
     "moic": "5.16×"
    },
    {
     "key": "gccia",
     "name": "GCC Interconnection",
     "geo": "Gulf grid",
     "cur": "US$",
     "ebitda": 88.4,
     "ev": 1502,
     "entry": 17,
     "exit": 16,
     "lev": 5,
     "growth": 2,
     "hold": 25,
     "rd": 5,
     "uirr": "6.9%",
     "lirr": "7.4%",
     "moic": "3.72×"
    },
    {
     "key": "garabi",
     "name": "Garabi",
     "geo": "Brazil ⇄ Argentina",
     "cur": "US$",
     "ebitda": 73.6,
     "ev": 704,
     "entry": 9.5,
     "exit": 9.5,
     "lev": 3.5,
     "growth": 4,
     "hold": 20,
     "rd": 9,
     "uirr": "10.3%",
     "lirr": "11.6%",
     "moic": "5.34×"
    },
    {
     "key": "cahora",
     "name": "Cahora Bassa HVDC",
     "geo": "Mozambique → South Africa",
     "cur": "US$",
     "ebitda": 312,
     "ev": 2683,
     "entry": 8.5,
     "exit": 8.6,
     "lev": 2,
     "growth": 3,
     "hold": 20,
     "rd": 9.5,
     "uirr": "10.4%",
     "lirr": "11.1%",
     "moic": "4.35×"
    }
   ]
  },
  {
   "cls": "Energy & Utilities",
   "name": "Gas transmission",
   "url": "gas-transmission.html",
   "assets": [
    {
     "key": "snam",
     "name": "Snam",
     "geo": "Italy",
     "cur": "€",
     "ebitda": 2288,
     "ev": 22000,
     "entry": 9.5,
     "exit": 11,
     "lev": 6,
     "growth": 3,
     "hold": 25,
     "rd": 5,
     "uirr": "6.3%",
     "lirr": "8.1%",
     "moic": "6.04×"
    },
    {
     "key": "williams",
     "name": "Williams (Transco)",
     "geo": "US Gulf → North-East",
     "cur": "US$",
     "ebitda": 2260,
     "ev": 20000,
     "entry": 9,
     "exit": 11,
     "lev": 5,
     "growth": 4,
     "hold": 25,
     "rd": 5,
     "uirr": "8.8%",
     "lirr": "11.8%",
     "moic": "9.11×"
    },
    {
     "key": "tgs",
     "name": "TGS",
     "geo": "Argentina",
     "cur": "US$",
     "ebitda": 435,
     "ev": 3000,
     "entry": 7,
     "exit": 8,
     "lev": 3,
     "growth": 6,
     "hold": 25,
     "rd": 12,
     "uirr": "10.3%",
     "lirr": "11.0%",
     "moic": "10.54×"
    },
    {
     "key": "apa",
     "name": "APA Group",
     "geo": "East-coast Australia",
     "cur": "A$",
     "ebitda": 2575,
     "ev": 25000,
     "entry": 9.5,
     "exit": 12,
     "lev": 6,
     "growth": 4,
     "hold": 25,
     "rd": 5,
     "uirr": "8.3%",
     "lirr": "11.6%",
     "moic": "9.60×"
    },
    {
     "key": "aramco",
     "name": "Aramco Gas Pipelines",
     "geo": "Saudi Arabia",
     "cur": "US$",
     "ebitda": 3390,
     "ev": 30000,
     "entry": 9,
     "exit": 9,
     "lev": 5,
     "growth": 2,
     "hold": 20,
     "rd": 4.5,
     "uirr": "10.4%",
     "lirr": "14.8%",
     "moic": "5.99×"
    },
    {
     "key": "pipechina",
     "name": "PipeChina",
     "geo": "China",
     "cur": "$",
     "ebitda": 55200,
     "ev": 600000,
     "entry": 11,
     "exit": 11,
     "lev": 4,
     "growth": 5,
     "hold": 25,
     "rd": 4,
     "uirr": "8.1%",
     "lirr": "9.4%",
     "moic": "6.66×"
    }
   ]
  },
  {
   "cls": "Energy & Utilities",
   "name": "Gas distribution",
   "url": "gas-distribution.html",
   "assets": [
    {
     "key": "cadent",
     "name": "Cadent",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 972,
     "ev": 9000,
     "entry": 9.5,
     "exit": 9,
     "lev": 6,
     "growth": 1.5,
     "hold": 25,
     "rd": 5,
     "uirr": "4.5%",
     "lirr": "5.3%",
     "moic": "3.24×"
    },
    {
     "key": "socalgas",
     "name": "SoCalGas",
     "geo": "Southern California, USA",
     "cur": "US$",
     "ebitda": 2220,
     "ev": 20000,
     "entry": 9,
     "exit": 9,
     "lev": 5,
     "growth": 2,
     "hold": 25,
     "rd": 5,
     "uirr": "5.5%",
     "lirr": "6.8%",
     "moic": "3.91×"
    },
    {
     "key": "comgas",
     "name": "Comgás",
     "geo": "São Paulo, Brazil",
     "cur": "R$",
     "ebitda": 1125,
     "ev": 9000,
     "entry": 8,
     "exit": 9,
     "lev": 4,
     "growth": 5,
     "hold": 25,
     "rd": 9,
     "uirr": "7.7%",
     "lirr": "8.3%",
     "moic": "7.49×"
    },
    {
     "key": "agig",
     "name": "Australian Gas Networks",
     "geo": "South Australia",
     "cur": "A$",
     "ebitda": 756,
     "ev": 7000,
     "entry": 9.5,
     "exit": 9,
     "lev": 6,
     "growth": 1.5,
     "hold": 25,
     "rd": 5,
     "uirr": "4.5%",
     "lirr": "5.6%",
     "moic": "3.37×"
    },
    {
     "key": "egypt",
     "name": "Town Gas (Egypt)",
     "geo": "Greater Cairo, Egypt",
     "cur": "US$",
     "ebitda": 536,
     "ev": 4000,
     "entry": 7.5,
     "exit": 9,
     "lev": 4,
     "growth": 7,
     "hold": 25,
     "rd": 9,
     "uirr": "9.1%",
     "lirr": "9.7%",
     "moic": "12.73×"
    },
    {
     "key": "enn",
     "name": "ENN Energy",
     "geo": "China",
     "cur": "$",
     "ebitda": 8240,
     "ev": 80000,
     "entry": 9.5,
     "exit": 10,
     "lev": 4,
     "growth": 6,
     "hold": 25,
     "rd": 5,
     "uirr": "8.0%",
     "lirr": "9.1%",
     "moic": "7.81×"
    }
   ]
  },
  {
   "cls": "Energy & Utilities",
   "name": "Water & wastewater",
   "url": "water-wastewater.html",
   "assets": [
    {
     "key": "unitedutils",
     "name": "United Utilities",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 1470,
     "ev": 15000,
     "entry": 10,
     "exit": 10,
     "lev": 6,
     "growth": 5,
     "hold": 25,
     "rd": 5,
     "uirr": "5.3%",
     "lirr": "6.0%",
     "moic": "5.69×"
    },
    {
     "key": "amwater",
     "name": "American Water",
     "geo": "US (multi-state)",
     "cur": "US$",
     "ebitda": 2260,
     "ev": 20000,
     "entry": 9,
     "exit": 11,
     "lev": 5,
     "growth": 5,
     "hold": 25,
     "rd": 5,
     "uirr": "6.3%",
     "lirr": "7.3%",
     "moic": "7.49×"
    },
    {
     "key": "sabesp",
     "name": "Sabesp",
     "geo": "São Paulo, Brazil",
     "cur": "R$",
     "ebitda": 7200,
     "ev": 60000,
     "entry": 8.5,
     "exit": 9,
     "lev": 4,
     "growth": 6,
     "hold": 25,
     "rd": 9,
     "uirr": "7.3%",
     "lirr": "7.7%",
     "moic": "7.73×"
    },
    {
     "key": "sydneywater",
     "name": "Sydney Water",
     "geo": "Sydney, Australia",
     "cur": "A$",
     "ebitda": 1960,
     "ev": 20000,
     "entry": 10,
     "exit": 10,
     "lev": 6,
     "growth": 4,
     "hold": 25,
     "rd": 5,
     "uirr": "4.5%",
     "lirr": "5.0%",
     "moic": "4.27×"
    },
    {
     "key": "nwc",
     "name": "National Water (Saudi)",
     "geo": "Saudi Arabia",
     "cur": "$",
     "ebitda": 8640,
     "ev": 80000,
     "entry": 9.5,
     "exit": 10,
     "lev": 5,
     "growth": 7,
     "hold": 25,
     "rd": 4.5,
     "uirr": "7.9%",
     "lirr": "9.0%",
     "moic": "10.94×"
    },
    {
     "key": "bewg",
     "name": "Beijing Enterprises Water",
     "geo": "China",
     "cur": "$",
     "ebitda": 9270,
     "ev": 90000,
     "entry": 9.5,
     "exit": 10,
     "lev": 4,
     "growth": 5,
     "hold": 25,
     "rd": 5,
     "uirr": "6.0%",
     "lirr": "6.6%",
     "moic": "5.32×"
    }
   ]
  },
  {
   "cls": "Energy & Utilities",
   "name": "Last-mile water",
   "url": "last-mile-water.html",
   "assets": [
    {
     "key": "iwnl",
     "name": "Independent Water Networks",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 8,
     "ev": 150,
     "entry": 19,
     "exit": 16,
     "lev": 5,
     "growth": 5,
     "hold": 25,
     "rd": 5.5,
     "uirr": "6.6%",
     "lirr": "7.1%",
     "moic": "4.60×"
    },
    {
     "key": "gwr",
     "name": "Global Water Resources",
     "geo": "Arizona, USA",
     "cur": "US$",
     "ebitda": 18.5,
     "ev": 230,
     "entry": 12.5,
     "exit": 13,
     "lev": 5,
     "growth": 5,
     "hold": 25,
     "rd": 5,
     "uirr": "6.8%",
     "lirr": "7.7%",
     "moic": "5.87×"
    },
    {
     "key": "aegea",
     "name": "Aegea Saneamento",
     "geo": "Brazil",
     "cur": "R$",
     "ebitda": 1509,
     "ev": 14000,
     "entry": 9.5,
     "exit": 9,
     "lev": 4,
     "growth": 5,
     "hold": 15,
     "rd": 9,
     "uirr": "7.8%",
     "lirr": "8.6%",
     "moic": "3.27×"
    },
    {
     "key": "flow",
     "name": "Flow Systems",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 10.5,
     "ev": 125,
     "entry": 12,
     "exit": 13,
     "lev": 5,
     "growth": 6,
     "hold": 20,
     "rd": 6,
     "uirr": "8.4%",
     "lirr": "9.7%",
     "moic": "5.93×"
    },
    {
     "key": "enowawater",
     "name": "ENOWA · NEOM (water)",
     "geo": "Saudi Arabia",
     "cur": "$",
     "ebitda": 88.7,
     "ev": 6804,
     "entry": 12,
     "exit": 12,
     "lev": 5,
     "growth": 10,
     "hold": 30,
     "rd": 4.5,
     "uirr": "5.2%",
     "lirr": "5.2%",
     "moic": "3.88×"
    },
    {
     "key": "cwa",
     "name": "China Water Affairs",
     "geo": "China",
     "cur": "$",
     "ebitda": 1286,
     "ev": 20000,
     "entry": 15.5,
     "exit": 10,
     "lev": 5,
     "growth": 6,
     "hold": 25,
     "rd": 4.5,
     "uirr": "5.7%",
     "lirr": "6.1%",
     "moic": "4.18×"
    }
   ]
  },
  {
   "cls": "Energy & Utilities",
   "name": "Heat networks",
   "url": "heat-networks.html",
   "assets": [
    {
     "key": "copen",
     "name": "Copenhagen district heating",
     "geo": "Copenhagen, Denmark",
     "cur": "€",
     "ebitda": 138,
     "ev": 2199,
     "entry": 16,
     "exit": 13,
     "lev": 6,
     "growth": 2,
     "hold": 25,
     "rd": 4.5,
     "uirr": "4.6%",
     "lirr": "5.0%",
     "moic": "2.75×"
    },
    {
     "key": "vicinity",
     "name": "Vicinity Energy",
     "geo": "US cities (e.g. Boston)",
     "cur": "US$",
     "ebitda": 132,
     "ev": 1500,
     "entry": 11.5,
     "exit": 14,
     "lev": 5,
     "growth": 4,
     "hold": 25,
     "rd": 5,
     "uirr": "8.0%",
     "lirr": "9.4%",
     "moic": "6.87×"
    },
    {
     "key": "veolia",
     "name": "Veolia district energy",
     "geo": "Latin America",
     "cur": "US$",
     "ebitda": 47.5,
     "ev": 550,
     "entry": 11.5,
     "exit": 11,
     "lev": 4,
     "growth": 6,
     "hold": 20,
     "rd": 9,
     "uirr": "8.1%",
     "lirr": "8.6%",
     "moic": "4.76×"
    },
    {
     "key": "sydney",
     "name": "Sydney precinct thermal",
     "geo": "Sydney, Australia",
     "cur": "A$",
     "ebitda": 46.9,
     "ev": 600,
     "entry": 13,
     "exit": 13,
     "lev": 5,
     "growth": 4,
     "hold": 18,
     "rd": 6,
     "uirr": "6.7%",
     "lirr": "7.6%",
     "moic": "3.40×"
    },
    {
     "key": "tabreed",
     "name": "Tabreed",
     "geo": "United Arab Emirates",
     "cur": "$",
     "ebitda": 150,
     "ev": 2098,
     "entry": 14,
     "exit": 12,
     "lev": 6,
     "growth": 4,
     "hold": 25,
     "rd": 5,
     "uirr": "8.8%",
     "lirr": "10.3%",
     "moic": "6.19×"
    },
    {
     "key": "chinadh",
     "name": "Municipal district heating",
     "geo": "Northern China",
     "cur": "$",
     "ebitda": 262,
     "ev": 4500,
     "entry": 17,
     "exit": 10,
     "lev": 5,
     "growth": 5,
     "hold": 25,
     "rd": 4,
     "uirr": "6.0%",
     "lirr": "6.6%",
     "moic": "3.78×"
    }
   ]
  },
  {
   "cls": "Transport",
   "name": "Roads",
   "url": "roads.html",
   "assets": [
    {
     "key": "autostrade",
     "name": "Autostrade per l'Italia",
     "geo": "Italy",
     "cur": "€",
     "ebitda": 96.1,
     "ev": 1250,
     "entry": 13,
     "exit": 13,
     "lev": 6,
     "growth": 2.5,
     "hold": 28,
     "rd": 5,
     "uirr": "6.9%",
     "lirr": "8.2%",
     "moic": "5.36×"
    },
    {
     "key": "etr407",
     "name": "407 ETR",
     "geo": "Toronto, Canada",
     "cur": "$",
     "ebitda": 203,
     "ev": 3650,
     "entry": 18,
     "exit": 18,
     "lev": 6,
     "growth": 4,
     "hold": 30,
     "rd": 5,
     "uirr": "7.6%",
     "lirr": "8.5%",
     "moic": "6.83×"
    },
    {
     "key": "ccr",
     "name": "CCR",
     "geo": "Brazil",
     "cur": "R$",
     "ebitda": 107,
     "ev": 850,
     "entry": 8,
     "exit": 9,
     "lev": 4,
     "growth": 4,
     "hold": 15,
     "rd": 9,
     "uirr": "9.3%",
     "lirr": "11.0%",
     "moic": "4.18×"
    },
    {
     "key": "transurban",
     "name": "Transurban",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 134,
     "ev": 1897,
     "entry": 14,
     "exit": 15,
     "lev": 6,
     "growth": 3.5,
     "hold": 26,
     "rd": 5.5,
     "uirr": "7.5%",
     "lirr": "8.8%",
     "moic": "5.90×"
    },
    {
     "key": "gulfppp",
     "name": "Gulf Highway PPP",
     "geo": "Saudi Arabia / UAE",
     "cur": "$",
     "ebitda": 576,
     "ev": 7000,
     "entry": 12,
     "exit": 13,
     "lev": 7,
     "growth": 1.5,
     "hold": 25,
     "rd": 5,
     "uirr": "8.7%",
     "lirr": "11.3%",
     "moic": "6.23×"
    },
    {
     "key": "expressway",
     "name": "Jiangsu Expressway",
     "geo": "Yangtze Delta, China",
     "cur": "$",
     "ebitda": 81,
     "ev": 1050,
     "entry": 13,
     "exit": 12,
     "lev": 5,
     "growth": 3,
     "hold": 28,
     "rd": 4,
     "uirr": "7.2%",
     "lirr": "8.6%",
     "moic": "5.41×"
    }
   ]
  },
  {
   "cls": "Transport",
   "name": "Rail infrastructure",
   "url": "rail-infrastructure.html",
   "assets": [
    {
     "key": "hs2",
     "name": "HS2 · High Speed 2",
     "geo": "London ⇄ Birmingham",
     "cur": "£",
     "ebitda": 2255,
     "ev": 52000,
     "entry": 23,
     "exit": 6,
     "lev": 2,
     "growth": 2,
     "hold": 30,
     "rd": 5,
     "uirr": "2.6%",
     "lirr": "2.5%",
     "moic": "1.63×"
    },
    {
     "key": "tgv",
     "name": "TGV · LGV Sud-Est & Méditerranée",
     "geo": "Paris ⇄ Lyon ⇄ Marseille",
     "cur": "€",
     "ebitda": 1478,
     "ev": 16000,
     "entry": 11,
     "exit": 11,
     "lev": 4,
     "growth": 2,
     "hold": 25,
     "rd": 4,
     "uirr": "7.7%",
     "lirr": "9.2%",
     "moic": "4.62×"
    },
    {
     "key": "tokaido",
     "name": "Tōkaidō Shinkansen",
     "geo": "Tokyo ⇄ Nagoya ⇄ Osaka",
     "cur": "$",
     "ebitda": 616669,
     "ev": 5400000,
     "entry": 9,
     "exit": 9,
     "lev": 3,
     "growth": 1.5,
     "hold": 25,
     "rd": 1.5,
     "uirr": "7.0%",
     "lirr": "8.8%",
     "moic": "4.12×"
    },
    {
     "key": "brightline",
     "name": "Brightline Florida",
     "geo": "Miami ⇄ Orlando",
     "cur": "$",
     "ebitda": 144,
     "ev": 6001,
     "entry": 14,
     "exit": 14,
     "lev": 5,
     "growth": 7,
     "hold": 20,
     "rd": 8,
     "uirr": "3.2%",
     "lirr": "2.9%",
     "moic": "1.69×"
    },
    {
     "key": "haramain",
     "name": "Haramain High-Speed Railway",
     "geo": "Mecca ⇄ Jeddah ⇄ Medina",
     "cur": "$",
     "ebitda": 850,
     "ev": 30000,
     "entry": 11,
     "exit": 11,
     "lev": 2,
     "growth": 3,
     "hold": 30,
     "rd": 5,
     "uirr": "3.4%",
     "lirr": "3.3%",
     "moic": "1.99×"
    },
    {
     "key": "beijingshanghai",
     "name": "Beijing–Shanghai HSR",
     "geo": "Beijing ⇄ Jinan ⇄ Shanghai",
     "cur": "$",
     "ebitda": 20843,
     "ev": 290000,
     "entry": 14,
     "exit": 12,
     "lev": 2,
     "growth": 4,
     "hold": 25,
     "rd": 4,
     "uirr": "8.0%",
     "lirr": "8.5%",
     "moic": "4.47×"
    }
   ]
  },
  {
   "cls": "Transport",
   "name": "Airports",
   "url": "airports.html",
   "assets": [
    {
     "key": "heathrow",
     "name": "London Heathrow",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 1995,
     "ev": 20000,
     "entry": 10,
     "exit": 10,
     "lev": 7,
     "growth": 3,
     "hold": 25,
     "rd": 5,
     "uirr": "8.4%",
     "lirr": "14.0%",
     "moic": "9.16×"
    },
    {
     "key": "atlanta",
     "name": "Hartsfield–Jackson Atlanta",
     "geo": "Georgia, USA",
     "cur": "US$",
     "ebitda": 419,
     "ev": 4500,
     "entry": 10.5,
     "exit": 10,
     "lev": 4,
     "growth": 2,
     "hold": 25,
     "rd": 4.5,
     "uirr": "9.1%",
     "lirr": "11.0%",
     "moic": "5.01×"
    },
    {
     "key": "lima",
     "name": "Lima Jorge Chávez",
     "geo": "Peru",
     "cur": "US$",
     "ebitda": 278,
     "ev": 2098,
     "entry": 7.5,
     "exit": 9,
     "lev": 4,
     "growth": 4,
     "hold": 25,
     "rd": 8.5,
     "uirr": "11.7%",
     "lirr": "14.1%",
     "moic": "11.10×"
    },
    {
     "key": "sydney",
     "name": "Sydney Airport",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 1359,
     "ev": 30000,
     "entry": 22,
     "exit": 22,
     "lev": 8,
     "growth": 4,
     "hold": 40,
     "rd": 5,
     "uirr": "6.5%",
     "lirr": "7.2%",
     "moic": "9.79×"
    },
    {
     "key": "dubai",
     "name": "Dubai International (DXB)",
     "geo": "Dubai, UAE",
     "cur": "US$",
     "ebitda": 1826,
     "ev": 21000,
     "entry": 11.5,
     "exit": 11,
     "lev": 5,
     "growth": 3,
     "hold": 25,
     "rd": 5,
     "uirr": "9.7%",
     "lirr": "12.0%",
     "moic": "6.41×"
    },
    {
     "key": "beijing",
     "name": "Beijing Capital (PEK)",
     "geo": "Beijing, China",
     "cur": "$",
     "ebitda": 2949,
     "ev": 24000,
     "entry": 8,
     "exit": 10,
     "lev": 3,
     "growth": 4,
     "hold": 25,
     "rd": 4,
     "uirr": "12.2%",
     "lirr": "15.1%",
     "moic": "9.29×"
    }
   ]
  },
  {
   "cls": "Transport",
   "name": "Ports",
   "url": "ports.html",
   "assets": [
    {
     "key": "rotterdam",
     "name": "Port of Rotterdam",
     "geo": "Netherlands",
     "cur": "€",
     "ebitda": 562,
     "ev": 9000,
     "entry": 16,
     "exit": 12,
     "lev": 5,
     "growth": 2,
     "hold": 25,
     "rd": 4,
     "uirr": "5.7%",
     "lirr": "6.5%",
     "moic": "3.07×"
    },
    {
     "key": "la",
     "name": "Port of Los Angeles",
     "geo": "San Pedro Bay, USA",
     "cur": "US$",
     "ebitda": 430,
     "ev": 7000,
     "entry": 16.5,
     "exit": 12,
     "lev": 4,
     "growth": 2,
     "hold": 25,
     "rd": 4.5,
     "uirr": "7.0%",
     "lirr": "7.6%",
     "moic": "3.36×"
    },
    {
     "key": "cartagena",
     "name": "Port of Cartagena",
     "geo": "Colombia",
     "cur": "US$",
     "ebitda": 214,
     "ev": 1700,
     "entry": 8,
     "exit": 8,
     "lev": 4,
     "growth": 4,
     "hold": 25,
     "rd": 9,
     "uirr": "11.6%",
     "lirr": "13.7%",
     "moic": "9.74×"
    },
    {
     "key": "melbourne",
     "name": "Port of Melbourne",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 407,
     "ev": 9700,
     "entry": 24,
     "exit": 22,
     "lev": 7,
     "growth": 3,
     "hold": 40,
     "rd": 5,
     "uirr": "5.6%",
     "lirr": "6.1%",
     "moic": "6.22×"
    },
    {
     "key": "jebelali",
     "name": "Jebel Ali Port",
     "geo": "Dubai, UAE",
     "cur": "US$",
     "ebitda": 1424,
     "ev": 15000,
     "entry": 10.5,
     "exit": 11,
     "lev": 5,
     "growth": 3,
     "hold": 25,
     "rd": 5,
     "uirr": "10.8%",
     "lirr": "14.1%",
     "moic": "7.78×"
    },
    {
     "key": "shanghai",
     "name": "Port of Shanghai",
     "geo": "Yangshan, China",
     "cur": "$",
     "ebitda": 19037,
     "ev": 130000,
     "entry": 7,
     "exit": 9,
     "lev": 3,
     "growth": 3,
     "hold": 25,
     "rd": 4,
     "uirr": "13.1%",
     "lirr": "17.9%",
     "moic": "9.91×"
    }
   ]
  },
  {
   "cls": "Transport",
   "name": "Rolling stock",
   "url": "rolling-stock.html",
   "assets": [
    {
     "key": "angel",
     "name": "Angel Trains",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 66,
     "ev": 1330,
     "entry": 20,
     "exit": 13,
     "lev": 6,
     "growth": 2.5,
     "hold": 28,
     "rd": 5,
     "uirr": "5.1%",
     "lirr": "5.4%",
     "moic": "3.05×"
    },
    {
     "key": "gatx",
     "name": "GATX",
     "geo": "United States",
     "cur": "US$",
     "ebitda": 433,
     "ev": 4800,
     "entry": 11,
     "exit": 11,
     "lev": 5,
     "growth": 3,
     "hold": 22,
     "rd": 5.5,
     "uirr": "9.1%",
     "lirr": "11.5%",
     "moic": "5.39×"
    },
    {
     "key": "lima",
     "name": "Lima Metro Line 2",
     "geo": "Lima, Peru",
     "cur": "US$",
     "ebitda": 38.6,
     "ev": 440,
     "entry": 11.5,
     "exit": 10,
     "lev": 5,
     "growth": 2,
     "hold": 18,
     "rd": 9,
     "uirr": "7.4%",
     "lirr": "8.0%",
     "moic": "3.00×"
    },
    {
     "key": "sydney",
     "name": "Sydney Growth Trains",
     "geo": "New South Wales, Australia",
     "cur": "A$",
     "ebitda": 56.2,
     "ev": 660,
     "entry": 11.5,
     "exit": 13,
     "lev": 7,
     "growth": 2.5,
     "hold": 28,
     "rd": 5,
     "uirr": "8.4%",
     "lirr": "11.3%",
     "moic": "8.68×"
    },
    {
     "key": "riyadh",
     "name": "Riyadh Metro",
     "geo": "Saudi Arabia",
     "cur": "$",
     "ebitda": 370,
     "ev": 4300,
     "entry": 11.5,
     "exit": 12,
     "lev": 5,
     "growth": 2.5,
     "hold": 25,
     "rd": 4.5,
     "uirr": "10.7%",
     "lirr": "13.6%",
     "moic": "6.79×"
    },
    {
     "key": "crrc",
     "name": "CRRC Financial Leasing",
     "geo": "China",
     "cur": "$",
     "ebitda": 377,
     "ev": 9000,
     "entry": 24,
     "exit": 10,
     "lev": 4,
     "growth": 5,
     "hold": 25,
     "rd": 3.5,
     "uirr": "5.8%",
     "lirr": "6.2%",
     "moic": "3.12×"
    }
   ]
  },
  {
   "cls": "Transport",
   "name": "EV charging",
   "url": "ev-charging.html",
   "assets": [
    {
     "key": "fastned",
     "name": "Fastned",
     "geo": "Netherlands · Europe",
     "cur": "€",
     "ebitda": 2.3,
     "ev": 32,
     "entry": 14,
     "exit": 10,
     "lev": 4,
     "growth": 8,
     "hold": 16,
     "rd": 5,
     "uirr": "10.7%",
     "lirr": "12.0%",
     "moic": "4.61×"
    },
    {
     "key": "evgo",
     "name": "EVgo",
     "geo": "United States",
     "cur": "US$",
     "ebitda": 4.5,
     "ev": 73,
     "entry": 16,
     "exit": 10,
     "lev": 4,
     "growth": 9,
     "hold": 15,
     "rd": 6,
     "uirr": "10.1%",
     "lirr": "10.9%",
     "moic": "3.82×"
    },
    {
     "key": "enelx",
     "name": "Enel X Way",
     "geo": "Latin America",
     "cur": "US$",
     "ebitda": 0.9,
     "ev": 19,
     "entry": 21,
     "exit": 9,
     "lev": 3,
     "growth": 11,
     "hold": 14,
     "rd": 9,
     "uirr": "7.2%",
     "lirr": "7.4%",
     "moic": "2.46×"
    },
    {
     "key": "evie",
     "name": "Evie Networks",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 1.4,
     "ev": 22,
     "entry": 15.5,
     "exit": 11,
     "lev": 4,
     "growth": 8,
     "hold": 16,
     "rd": 6,
     "uirr": "9.3%",
     "lirr": "10.0%",
     "moic": "3.83×"
    },
    {
     "key": "eviq",
     "name": "EVIQ",
     "geo": "Saudi Arabia",
     "cur": "$",
     "ebitda": 2,
     "ev": 40,
     "entry": 20,
     "exit": 12,
     "lev": 4,
     "growth": 10,
     "hold": 18,
     "rd": 5,
     "uirr": "11.7%",
     "lirr": "12.4%",
     "moic": "5.79×"
    },
    {
     "key": "starcharge",
     "name": "Star Charge",
     "geo": "China",
     "cur": "$",
     "ebitda": 46.1,
     "ev": 450,
     "entry": 10,
     "exit": 11,
     "lev": 4,
     "growth": 7,
     "hold": 15,
     "rd": 4,
     "uirr": "13.9%",
     "lirr": "17.2%",
     "moic": "6.87×"
    }
   ]
  },
  {
   "cls": "Transport",
   "name": "Bridges",
   "url": "bridges.html",
   "assets": [
    {
     "key": "oresund",
     "name": "Øresund Bridge",
     "geo": "Denmark ⇄ Sweden",
     "cur": "$",
     "ebitda": 2175,
     "ev": 19600,
     "entry": 9,
     "exit": 10,
     "lev": 6,
     "growth": 2,
     "hold": 25,
     "rd": 4,
     "uirr": "10.4%",
     "lirr": "18.7%",
     "moic": "10.06×"
    },
    {
     "key": "confed",
     "name": "Confederation Bridge",
     "geo": "New Brunswick ⇄ PEI",
     "cur": "$",
     "ebitda": 69.3,
     "ev": 1000,
     "entry": 14.5,
     "exit": 6,
     "lev": 7,
     "growth": 2,
     "hold": 30,
     "rd": 5,
     "uirr": "5.5%",
     "lirr": "6.4%",
     "moic": "3.58×"
    },
    {
     "key": "rioniteroi",
     "name": "Rio–Niterói Bridge",
     "geo": "Rio de Janeiro ⇄ Niterói",
     "cur": "R$",
     "ebitda": 317,
     "ev": 2200,
     "entry": 7,
     "exit": 8,
     "lev": 3.5,
     "growth": 4,
     "hold": 20,
     "rd": 12,
     "uirr": "13.0%",
     "lirr": "15.2%",
     "moic": "8.13×"
    },
    {
     "key": "sydney",
     "name": "Sydney Harbour Bridge",
     "geo": "Sydney, Australia",
     "cur": "A$",
     "ebitda": 52.7,
     "ev": 1504,
     "entry": 16,
     "exit": 16,
     "lev": 5,
     "growth": 2.5,
     "hold": 25,
     "rd": 5,
     "uirr": "2.7%",
     "lirr": "2.5%",
     "moic": "1.70×"
    },
    {
     "key": "kingfahd",
     "name": "King Fahd Causeway",
     "geo": "Saudi Arabia ⇄ Bahrain",
     "cur": "$",
     "ebitda": 379,
     "ev": 4000,
     "entry": 10.5,
     "exit": 11,
     "lev": 3,
     "growth": 2,
     "hold": 25,
     "rd": 5,
     "uirr": "11.0%",
     "lirr": "12.5%",
     "moic": "5.66×"
    },
    {
     "key": "hzmb",
     "name": "Hong Kong–Zhuhai–Macau Bridge",
     "geo": "Pearl River Estuary",
     "cur": "$",
     "ebitda": 215,
     "ev": 70001,
     "entry": 10,
     "exit": 10,
     "lev": 2,
     "growth": 5,
     "hold": 30,
     "rd": 4,
     "uirr": "-5.2%",
     "lirr": "-5.3%",
     "moic": "0.24×"
    }
   ]
  },
  {
   "cls": "Digital Infrastructure",
   "name": "Fibre networks",
   "url": "fibre-networks.html",
   "assets": [
    {
     "key": "cityfibre",
     "name": "CityFibre",
     "geo": "United Kingdom · Europe",
     "cur": "£",
     "ebitda": 153,
     "ev": 1994,
     "entry": 13,
     "exit": 12,
     "lev": 5,
     "growth": 4,
     "hold": 16,
     "rd": 7,
     "uirr": "7.9%",
     "lirr": "8.8%",
     "moic": "3.24×"
    },
    {
     "key": "frontier",
     "name": "Frontier Communications",
     "geo": "United States",
     "cur": "US$",
     "ebitda": 1322,
     "ev": 17200,
     "entry": 13,
     "exit": 11,
     "lev": 5,
     "growth": 3.5,
     "hold": 14,
     "rd": 7,
     "uirr": "7.2%",
     "lirr": "7.8%",
     "moic": "2.53×"
    },
    {
     "key": "fibrasil",
     "name": "FiBrasil",
     "geo": "Brazil",
     "cur": "R$",
     "ebitda": 832,
     "ev": 10100,
     "entry": 12,
     "exit": 10,
     "lev": 4,
     "growth": 5.5,
     "hold": 14,
     "rd": 12,
     "uirr": "8.1%",
     "lirr": "8.2%",
     "moic": "2.79×"
    },
    {
     "key": "chorus",
     "name": "Chorus",
     "geo": "New Zealand",
     "cur": "$",
     "ebitda": 368,
     "ev": 4500,
     "entry": 12,
     "exit": 13,
     "lev": 6,
     "growth": 3,
     "hold": 20,
     "rd": 6,
     "uirr": "7.8%",
     "lirr": "9.4%",
     "moic": "4.59×"
    },
    {
     "key": "etisalat",
     "name": "e& (Etisalat)",
     "geo": "United Arab Emirates",
     "cur": "$",
     "ebitda": 2742,
     "ev": 30200,
     "entry": 11,
     "exit": 11,
     "lev": 4,
     "growth": 2.5,
     "hold": 18,
     "rd": 5,
     "uirr": "9.5%",
     "lirr": "11.1%",
     "moic": "4.00×"
    },
    {
     "key": "chinatel",
     "name": "China Telecom",
     "geo": "China",
     "cur": "$",
     "ebitda": 48592,
     "ev": 530000,
     "entry": 11,
     "exit": 9,
     "lev": 4,
     "growth": 3.5,
     "hold": 15,
     "rd": 4,
     "uirr": "8.2%",
     "lirr": "10.0%",
     "moic": "3.08×"
    }
   ]
  },
  {
   "cls": "Digital Infrastructure",
   "name": "Mobile towers",
   "url": "mobile-towers.html",
   "assets": [
    {
     "key": "cellnex",
     "name": "Cellnex",
     "geo": "Western Europe",
     "cur": "€",
     "ebitda": 3031,
     "ev": 67470,
     "entry": 22.5,
     "exit": 21,
     "lev": 6,
     "growth": 5,
     "hold": 20,
     "rd": 4.5,
     "uirr": "7.6%",
     "lirr": "8.5%",
     "moic": "4.08×"
    },
    {
     "key": "amt",
     "name": "American Tower",
     "geo": "United States",
     "cur": "US$",
     "ebitda": 1647,
     "ev": 40500,
     "entry": 24.5,
     "exit": 22,
     "lev": 6,
     "growth": 5,
     "hold": 20,
     "rd": 4.75,
     "uirr": "8.2%",
     "lirr": "8.8%",
     "moic": "4.07×"
    },
    {
     "key": "highline",
     "name": "Highline do Brasil",
     "geo": "Brazil",
     "cur": "R$",
     "ebitda": 761,
     "ev": 16010,
     "entry": 21,
     "exit": 18,
     "lev": 5,
     "growth": 6,
     "hold": 15,
     "rd": 9,
     "uirr": "7.5%",
     "lirr": "7.8%",
     "moic": "2.83×"
    },
    {
     "key": "amplitel",
     "name": "Amplitel",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 230,
     "ev": 5750,
     "entry": 25,
     "exit": 24,
     "lev": 6,
     "growth": 4,
     "hold": 20,
     "rd": 5,
     "uirr": "6.3%",
     "lirr": "6.8%",
     "moic": "3.19×"
    },
    {
     "key": "tasc",
     "name": "TASC Towers",
     "geo": "MENA region",
     "cur": "US$",
     "ebitda": 137,
     "ev": 3395,
     "entry": 25,
     "exit": 19,
     "lev": 5,
     "growth": 6,
     "hold": 18,
     "rd": 6.5,
     "uirr": "7.6%",
     "lirr": "7.9%",
     "moic": "3.30×"
    },
    {
     "key": "chinatower",
     "name": "China Tower",
     "geo": "China",
     "cur": "$",
     "ebitda": 12220,
     "ev": 230960,
     "entry": 19,
     "exit": 18,
     "lev": 4,
     "growth": 4,
     "hold": 25,
     "rd": 3.5,
     "uirr": "7.1%",
     "lirr": "7.8%",
     "moic": "4.48×"
    }
   ]
  },
  {
   "cls": "Digital Infrastructure",
   "name": "Data centres",
   "url": "data-centres.html",
   "assets": [
    {
     "key": "equinix",
     "name": "Equinix",
     "geo": "interconnection · Europe",
     "cur": "US$",
     "ebitda": 4227,
     "ev": 62000,
     "entry": 14.5,
     "exit": 15,
     "lev": 5,
     "growth": 5,
     "hold": 15,
     "rd": 5,
     "uirr": "10.1%",
     "lirr": "12.0%",
     "moic": "3.95×"
    },
    {
     "key": "nova",
     "name": "Northern Virginia",
     "geo": "Ashburn · USA",
     "cur": "US$",
     "ebitda": 865,
     "ev": 12000,
     "entry": 14,
     "exit": 15,
     "lev": 5,
     "growth": 6,
     "hold": 12,
     "rd": 5.5,
     "uirr": "11.4%",
     "lirr": "13.9%",
     "moic": "3.75×"
    },
    {
     "key": "ascenty",
     "name": "Ascenty",
     "geo": "São Paulo · Brazil",
     "cur": "US$",
     "ebitda": 428,
     "ev": 3300,
     "entry": 7.5,
     "exit": 8,
     "lev": 4,
     "growth": 5,
     "hold": 20,
     "rd": 11,
     "uirr": "12.4%",
     "lirr": "14.9%",
     "moic": "8.36×"
    },
    {
     "key": "airtrunk",
     "name": "AirTrunk",
     "geo": "Sydney · Australia",
     "cur": "A$",
     "ebitda": 1461,
     "ev": 24000,
     "entry": 16.5,
     "exit": 16,
     "lev": 7,
     "growth": 4,
     "hold": 25,
     "rd": 5.5,
     "uirr": "7.9%",
     "lirr": "9.5%",
     "moic": "5.91×"
    },
    {
     "key": "khazna",
     "name": "Khazna Data Centers",
     "geo": "Abu Dhabi · UAE",
     "cur": "US$",
     "ebitda": 434,
     "ev": 5500,
     "entry": 12.5,
     "exit": 13,
     "lev": 4,
     "growth": 6,
     "hold": 20,
     "rd": 5.5,
     "uirr": "12.5%",
     "lirr": "14.3%",
     "moic": "7.23×"
    },
    {
     "key": "gds",
     "name": "GDS Holdings",
     "geo": "China",
     "cur": "$",
     "ebitda": 4804,
     "ev": 55000,
     "entry": 11.5,
     "exit": 10,
     "lev": 5,
     "growth": 6,
     "hold": 20,
     "rd": 4,
     "uirr": "11.0%",
     "lirr": "14.2%",
     "moic": "7.18×"
    }
   ]
  },
  {
   "cls": "Digital Infrastructure",
   "name": "Subsea cables",
   "url": "subsea-cables.html",
   "assets": [
    {
     "key": "aquacomms",
     "name": "Aqua Comms",
     "geo": "Ireland ↔ United States",
     "cur": "€",
     "ebitda": 156,
     "ev": 2098,
     "entry": 13.5,
     "exit": 13,
     "lev": 5,
     "growth": 2,
     "hold": 22,
     "rd": 5,
     "uirr": "7.5%",
     "lirr": "8.6%",
     "moic": "3.71×"
    },
    {
     "key": "google",
     "name": "Google subsea (Dunant / Grace Hopper)",
     "geo": "United States ↔ Europe",
     "cur": "$",
     "ebitda": 305,
     "ev": 3500,
     "entry": 11.5,
     "exit": 12,
     "lev": 5,
     "growth": 3,
     "hold": 24,
     "rd": 5,
     "uirr": "9.0%",
     "lirr": "11.2%",
     "moic": "5.99×"
    },
    {
     "key": "ellalink",
     "name": "EllaLink",
     "geo": "Portugal ↔ Brazil",
     "cur": "€",
     "ebitda": 133,
     "ev": 1480,
     "entry": 11,
     "exit": 13,
     "lev": 5,
     "growth": 3,
     "hold": 22,
     "rd": 5.5,
     "uirr": "9.4%",
     "lirr": "11.6%",
     "moic": "5.88×"
    },
    {
     "key": "southerncross",
     "name": "Southern Cross",
     "geo": "Australia ↔ NZ ↔ US",
     "cur": "US$",
     "ebitda": 156,
     "ev": 2039,
     "entry": 13,
     "exit": 13,
     "lev": 5,
     "growth": 3,
     "hold": 23,
     "rd": 5.5,
     "uirr": "7.5%",
     "lirr": "8.8%",
     "moic": "4.45×"
    },
    {
     "key": "twoafrica",
     "name": "2Africa / PEACE",
     "geo": "Middle East / around Africa",
     "cur": "US$",
     "ebitda": 120,
     "ev": 1400,
     "entry": 11.5,
     "exit": 11,
     "lev": 5,
     "growth": 4,
     "hold": 21,
     "rd": 6,
     "uirr": "9.9%",
     "lirr": "11.9%",
     "moic": "5.74×"
    },
    {
     "key": "asiacable",
     "name": "Asia Direct Cable / SEA-ME-WE 6",
     "geo": "Hong Kong ↔ Singapore",
     "cur": "US$",
     "ebitda": 140,
     "ev": 1740,
     "entry": 12.5,
     "exit": 12,
     "lev": 5,
     "growth": 4,
     "hold": 22,
     "rd": 5.5,
     "uirr": "8.9%",
     "lirr": "10.5%",
     "moic": "5.46×"
    }
   ]
  },
  {
   "cls": "Social Infrastructure",
   "name": "Hospitals",
   "url": "hospitals.html",
   "assets": [
    {
     "key": "nhs",
     "name": "UK NHS PFI hospital",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 34.3,
     "ev": 440,
     "entry": 13,
     "exit": 12,
     "lev": 4,
     "growth": 2.5,
     "hold": 18,
     "rd": 5,
     "uirr": "7.7%",
     "lirr": "8.9%",
     "moic": "3.19×"
    },
    {
     "key": "humber",
     "name": "Humber River Hospital",
     "geo": "Toronto, Canada",
     "cur": "$",
     "ebitda": 49.7,
     "ev": 680,
     "entry": 13.5,
     "exit": 11,
     "lev": 4,
     "growth": 2,
     "hold": 18,
     "rd": 5,
     "uirr": "6.3%",
     "lirr": "7.1%",
     "moic": "2.53×"
    },
    {
     "key": "chile",
     "name": "Chilean hospital concession",
     "geo": "Chile",
     "cur": "US$",
     "ebitda": 20.9,
     "ev": 266,
     "entry": 12.5,
     "exit": 9,
     "lev": 4,
     "growth": 2.5,
     "hold": 16,
     "rd": 8.5,
     "uirr": "6.5%",
     "lirr": "6.6%",
     "moic": "2.23×"
    },
    {
     "key": "northern",
     "name": "Northern Beaches Hospital",
     "geo": "New South Wales, Australia",
     "cur": "A$",
     "ebitda": 41.6,
     "ev": 570,
     "entry": 13.5,
     "exit": 11,
     "lev": 4,
     "growth": 2.5,
     "hold": 18,
     "rd": 5,
     "uirr": "6.5%",
     "lirr": "7.3%",
     "moic": "2.66×"
    },
    {
     "key": "turkey",
     "name": "Turkish city hospital (şehir hastanesi)",
     "geo": "Türkiye",
     "cur": "US$",
     "ebitda": 58,
     "ev": 770,
     "entry": 13.5,
     "exit": 9,
     "lev": 4,
     "growth": 3,
     "hold": 16,
     "rd": 8.5,
     "uirr": "6.7%",
     "lirr": "6.8%",
     "moic": "2.29×"
    },
    {
     "key": "china",
     "name": "Chinese social-capital hospital",
     "geo": "China",
     "cur": "$",
     "ebitda": 56,
     "ev": 750,
     "entry": 13.5,
     "exit": 10,
     "lev": 4,
     "growth": 3,
     "hold": 18,
     "rd": 4,
     "uirr": "7.3%",
     "lirr": "8.5%",
     "moic": "2.97×"
    }
   ]
  },
  {
   "cls": "Social Infrastructure",
   "name": "Schools",
   "url": "schools.html",
   "assets": [
    {
     "key": "ukbsf",
     "name": "UK BSF / PF2 schools bundle",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 7.9,
     "ev": 150,
     "entry": 19,
     "exit": 16,
     "lev": 5,
     "growth": 2.5,
     "hold": 25,
     "rd": 5,
     "uirr": "5.9%",
     "lirr": "6.2%",
     "moic": "3.33×"
    },
    {
     "key": "alberta",
     "name": "Alberta Schools P3",
     "geo": "Alberta, Canada",
     "cur": "$",
     "ebitda": 15.4,
     "ev": 260,
     "entry": 17,
     "exit": 15,
     "lev": 5,
     "growth": 2,
     "hold": 25,
     "rd": 5,
     "uirr": "6.0%",
     "lirr": "6.4%",
     "moic": "3.37×"
    },
    {
     "key": "belo",
     "name": "Belo Horizonte schools PPP",
     "geo": "Belo Horizonte, Brazil",
     "cur": "R$",
     "ebitda": 20.7,
     "ev": 234,
     "entry": 11.5,
     "exit": 9,
     "lev": 4,
     "growth": 3,
     "hold": 20,
     "rd": 9,
     "uirr": "8.3%",
     "lirr": "8.9%",
     "moic": "3.68×"
    },
    {
     "key": "nsw",
     "name": "NSW schools PPP",
     "geo": "New South Wales, Australia",
     "cur": "A$",
     "ebitda": 13.8,
     "ev": 250,
     "entry": 18,
     "exit": 15,
     "lev": 5,
     "growth": 2.5,
     "hold": 25,
     "rd": 5,
     "uirr": "5.8%",
     "lirr": "6.2%",
     "moic": "3.29×"
    },
    {
     "key": "egypt",
     "name": "Egypt / Gulf schools PPP",
     "geo": "Egypt · Gulf region",
     "cur": "US$",
     "ebitda": 9,
     "ev": 135,
     "entry": 15,
     "exit": 11,
     "lev": 4.5,
     "growth": 2.5,
     "hold": 23,
     "rd": 7,
     "uirr": "6.7%",
     "lirr": "7.0%",
     "moic": "3.26×"
    },
    {
     "key": "china",
     "name": "Chinese schools PPP",
     "geo": "China",
     "cur": "$",
     "ebitda": 50.4,
     "ev": 750,
     "entry": 15,
     "exit": 10,
     "lev": 4,
     "growth": 3,
     "hold": 22,
     "rd": 4,
     "uirr": "6.9%",
     "lirr": "7.6%",
     "moic": "3.26×"
    }
   ]
  },
  {
   "cls": "Social Infrastructure",
   "name": "Prisons",
   "url": "prisons.html",
   "assets": [
    {
     "key": "ukdbfo",
     "name": "UK custodial PFI/DBFO",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 16.2,
     "ev": 208,
     "entry": 13,
     "exit": 11,
     "lev": 5,
     "growth": 2.5,
     "hold": 16,
     "rd": 5,
     "uirr": "7.3%",
     "lirr": "8.8%",
     "moic": "2.85×"
    },
    {
     "key": "uscorr",
     "name": "US private corrections",
     "geo": "United States",
     "cur": "US$",
     "ebitda": 19.7,
     "ev": 240,
     "entry": 12,
     "exit": 10,
     "lev": 4,
     "growth": 2,
     "hold": 15,
     "rd": 6,
     "uirr": "6.9%",
     "lirr": "7.8%",
     "moic": "2.37×"
    },
    {
     "key": "chile",
     "name": "Chilean prison concession",
     "geo": "Chile / Latin America",
     "cur": "US$",
     "ebitda": 21,
     "ev": 245,
     "entry": 11.5,
     "exit": 9,
     "lev": 5,
     "growth": 2,
     "hold": 17,
     "rd": 9,
     "uirr": "7.1%",
     "lirr": "7.3%",
     "moic": "2.57×"
    },
    {
     "key": "clarence",
     "name": "Clarence Correctional Centre",
     "geo": "New South Wales, Australia",
     "cur": "A$",
     "ebitda": 39.4,
     "ev": 470,
     "entry": 12,
     "exit": 12,
     "lev": 6,
     "growth": 2.5,
     "hold": 16,
     "rd": 5,
     "uirr": "8.1%",
     "lirr": "10.8%",
     "moic": "3.69×"
    },
    {
     "key": "gulf",
     "name": "Gulf custodial PPP",
     "geo": "Gulf / Middle East",
     "cur": "US$",
     "ebitda": 21.4,
     "ev": 320,
     "entry": 15,
     "exit": 11,
     "lev": 5,
     "growth": 2.5,
     "hold": 18,
     "rd": 4.5,
     "uirr": "7.9%",
     "lirr": "9.2%",
     "moic": "2.99×"
    },
    {
     "key": "china",
     "name": "Chinese state custodial",
     "geo": "China",
     "cur": "$",
     "ebitda": 27.3,
     "ev": 324,
     "entry": 12,
     "exit": 10,
     "lev": 4,
     "growth": 3,
     "hold": 16,
     "rd": 3.5,
     "uirr": "8.4%",
     "lirr": "10.3%",
     "moic": "3.18×"
    }
   ]
  },
  {
   "cls": "Social Infrastructure",
   "name": "Courts",
   "url": "courts.html",
   "assets": [
    {
     "key": "uk",
     "name": "UK courts PFI",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 16.2,
     "ev": 210,
     "entry": 13,
     "exit": 12,
     "lev": 4,
     "growth": 2.5,
     "hold": 18,
     "rd": 5,
     "uirr": "7.8%",
     "lirr": "8.9%",
     "moic": "3.18×"
    },
    {
     "key": "ontario",
     "name": "Ontario courthouse P3",
     "geo": "Ontario, Canada",
     "cur": "$",
     "ebitda": 23.6,
     "ev": 320,
     "entry": 13.5,
     "exit": 11.5,
     "lev": 4,
     "growth": 2,
     "hold": 18,
     "rd": 5,
     "uirr": "6.7%",
     "lirr": "7.5%",
     "moic": "2.67×"
    },
    {
     "key": "chile",
     "name": "Chilean justice facility PPP",
     "geo": "Chile",
     "cur": "US$",
     "ebitda": 8.9,
     "ev": 104,
     "entry": 11.5,
     "exit": 10,
     "lev": 4,
     "growth": 2.5,
     "hold": 16,
     "rd": 8,
     "uirr": "7.8%",
     "lirr": "8.5%",
     "moic": "2.77×"
    },
    {
     "key": "australia",
     "name": "Australian court PPP",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 24.1,
     "ev": 335,
     "entry": 14,
     "exit": 11.5,
     "lev": 4,
     "growth": 2.5,
     "hold": 18,
     "rd": 5,
     "uirr": "6.6%",
     "lirr": "7.5%",
     "moic": "2.72×"
    },
    {
     "key": "gulf",
     "name": "Gulf justice complex PPP",
     "geo": "Gulf region",
     "cur": "US$",
     "ebitda": 21.3,
     "ev": 268,
     "entry": 12.5,
     "exit": 10,
     "lev": 4,
     "growth": 3,
     "hold": 16,
     "rd": 8,
     "uirr": "8.2%",
     "lirr": "8.7%",
     "moic": "2.80×"
    },
    {
     "key": "china",
     "name": "Chinese social-capital court complex",
     "geo": "China",
     "cur": "$",
     "ebitda": 22,
     "ev": 290,
     "entry": 13,
     "exit": 10,
     "lev": 4,
     "growth": 3,
     "hold": 18,
     "rd": 4,
     "uirr": "7.5%",
     "lirr": "8.7%",
     "moic": "3.04×"
    }
   ]
  },
  {
   "cls": "Social Infrastructure",
   "name": "Military",
   "url": "military.html",
   "assets": [
    {
     "key": "allenby",
     "name": "UK Project Allenby/Connaught",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 81.6,
     "ev": 1170,
     "entry": 14.5,
     "exit": 12,
     "lev": 4,
     "growth": 2.5,
     "hold": 20,
     "rd": 5,
     "uirr": "6.9%",
     "lirr": "7.6%",
     "moic": "3.02×"
    },
    {
     "key": "mhpi",
     "name": "US Military Housing Privatization (MHPI)",
     "geo": "United States",
     "cur": "US$",
     "ebitda": 169,
     "ev": 2078,
     "entry": 12.5,
     "exit": 12,
     "lev": 4,
     "growth": 2.5,
     "hold": 16,
     "rd": 5.5,
     "uirr": "8.1%",
     "lirr": "9.4%",
     "moic": "3.05×"
    },
    {
     "key": "latam",
     "name": "Latin-American defence estate PPP",
     "geo": "South America",
     "cur": "US$",
     "ebitda": 28.8,
     "ev": 300,
     "entry": 10.5,
     "exit": 9,
     "lev": 4,
     "growth": 2.5,
     "hold": 16,
     "rd": 8.5,
     "uirr": "8.5%",
     "lirr": "9.5%",
     "moic": "3.02×"
    },
    {
     "key": "dha",
     "name": "Defence Housing Australia accommodation",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 95.1,
     "ev": 1135,
     "entry": 12,
     "exit": 11,
     "lev": 4,
     "growth": 2.5,
     "hold": 16,
     "rd": 5,
     "uirr": "7.7%",
     "lirr": "9.1%",
     "moic": "2.92×"
    },
    {
     "key": "gulf",
     "name": "Gulf defence estate PPP",
     "geo": "Gulf region",
     "cur": "US$",
     "ebitda": 51.7,
     "ev": 750,
     "entry": 14.5,
     "exit": 9,
     "lev": 4,
     "growth": 3,
     "hold": 18,
     "rd": 8.5,
     "uirr": "6.2%",
     "lirr": "6.2%",
     "moic": "2.30×"
    },
    {
     "key": "china",
     "name": "Chinese state defence estate",
     "geo": "China",
     "cur": "$",
     "ebitda": 96.1,
     "ev": 1190,
     "entry": 12.5,
     "exit": 10,
     "lev": 4,
     "growth": 3,
     "hold": 16,
     "rd": 4,
     "uirr": "7.9%",
     "lirr": "9.5%",
     "moic": "2.95×"
    }
   ]
  },
  {
   "cls": "Social Infrastructure",
   "name": "Student accommodation",
   "url": "student-accommodation.html",
   "assets": [
    {
     "key": "unite",
     "name": "Unite Students",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 4.8,
     "ev": 72,
     "entry": 15,
     "exit": 17,
     "lev": 5,
     "growth": 3,
     "hold": 12,
     "rd": 5.5,
     "uirr": "8.6%",
     "lirr": "10.1%",
     "moic": "2.69×"
    },
    {
     "key": "acc",
     "name": "American Campus Communities",
     "geo": "United States",
     "cur": "US$",
     "ebitda": 6.1,
     "ev": 96,
     "entry": 15.5,
     "exit": 17,
     "lev": 6,
     "growth": 3,
     "hold": 12,
     "rd": 5.5,
     "uirr": "7.9%",
     "lirr": "9.5%",
     "moic": "2.58×"
    },
    {
     "key": "uliving",
     "name": "Uliving · Brazil PBSA",
     "geo": "Brazil",
     "cur": "R$",
     "ebitda": 4.3,
     "ev": 57,
     "entry": 13.5,
     "exit": 14,
     "lev": 4,
     "growth": 5,
     "hold": 12,
     "rd": 10,
     "uirr": "9.6%",
     "lirr": "10.5%",
     "moic": "2.87×"
    },
    {
     "key": "scape",
     "name": "Scape · Australia PBSA",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 8,
     "ev": 98,
     "entry": 12.5,
     "exit": 16,
     "lev": 5,
     "growth": 4,
     "hold": 12,
     "rd": 6,
     "uirr": "11.1%",
     "lirr": "13.9%",
     "moic": "3.82×"
    },
    {
     "key": "gulf",
     "name": "Gulf student housing",
     "geo": "UAE / Saudi Arabia",
     "cur": "$",
     "ebitda": 3.8,
     "ev": 60,
     "entry": 16,
     "exit": 16,
     "lev": 5,
     "growth": 5,
     "hold": 12,
     "rd": 6,
     "uirr": "10.9%",
     "lirr": "12.4%",
     "moic": "3.21×"
    },
    {
     "key": "china",
     "name": "Chinese student / co-living",
     "geo": "China",
     "cur": "$",
     "ebitda": 6.7,
     "ev": 90,
     "entry": 13.5,
     "exit": 17,
     "lev": 5,
     "growth": 4,
     "hold": 12,
     "rd": 4,
     "uirr": "10.6%",
     "lirr": "13.4%",
     "moic": "3.57×"
    }
   ]
  },
  {
   "cls": "Energy Transition",
   "name": "Onshore wind",
   "url": "onshore-wind.html",
   "assets": [
    {
     "key": "markbygden",
     "name": "Markbygden / Nordic onshore",
     "geo": "Northern Sweden",
     "cur": "€",
     "ebitda": 129,
     "ev": 1451,
     "entry": 11.5,
     "exit": 10,
     "lev": 5,
     "growth": 2,
     "hold": 13,
     "rd": 4.5,
     "uirr": "7.8%",
     "lirr": "10.3%",
     "moic": "2.65×"
    },
    {
     "key": "ercot",
     "name": "ERCOT wind",
     "geo": "Texas, USA",
     "cur": "US$",
     "ebitda": 25.8,
     "ev": 285,
     "entry": 11,
     "exit": 9,
     "lev": 4,
     "growth": 2,
     "hold": 13,
     "rd": 5.5,
     "uirr": "7.0%",
     "lirr": "8.2%",
     "moic": "2.25×"
    },
    {
     "key": "casadosventos",
     "name": "Casa dos Ventos",
     "geo": "Brazil",
     "cur": "R$",
     "ebitda": 418,
     "ev": 5300,
     "entry": 12.5,
     "exit": 9,
     "lev": 5,
     "growth": 5,
     "hold": 13,
     "rd": 11,
     "uirr": "7.8%",
     "lirr": "7.9%",
     "moic": "2.43×"
    },
    {
     "key": "goldenplains",
     "name": "Golden Plains / Macarthur",
     "geo": "Victoria, Australia",
     "cur": "A$",
     "ebitda": 126,
     "ev": 1560,
     "entry": 12.5,
     "exit": 10,
     "lev": 5,
     "growth": 3,
     "hold": 13,
     "rd": 6,
     "uirr": "6.9%",
     "lirr": "8.1%",
     "moic": "2.32×"
    },
    {
     "key": "dumat",
     "name": "Dumat Al Jandal",
     "geo": "Saudi Arabia",
     "cur": "$",
     "ebitda": 86.5,
     "ev": 1060,
     "entry": 12.5,
     "exit": 11,
     "lev": 6,
     "growth": 0,
     "hold": 14,
     "rd": 4,
     "uirr": "7.2%",
     "lirr": "9.4%",
     "moic": "2.51×"
    },
    {
     "key": "longyuan",
     "name": "Longyuan onshore",
     "geo": "Northern China",
     "cur": "$",
     "ebitda": 2974,
     "ev": 34000,
     "entry": 11.5,
     "exit": 10,
     "lev": 6,
     "growth": 3,
     "hold": 12,
     "rd": 3.5,
     "uirr": "8.2%",
     "lirr": "12.3%",
     "moic": "2.99×"
    }
   ]
  },
  {
   "cls": "Energy Transition",
   "name": "Offshore wind",
   "url": "offshore-wind.html",
   "assets": [
    {
     "key": "dogger",
     "name": "Dogger Bank / Hornsea",
     "geo": "North Sea, United Kingdom",
     "cur": "£",
     "ebitda": 1068,
     "ev": 13800,
     "entry": 13,
     "exit": 11,
     "lev": 6,
     "growth": 1.5,
     "hold": 15,
     "rd": 5,
     "uirr": "6.4%",
     "lirr": "7.8%",
     "moic": "2.49×"
    },
    {
     "key": "vineyard",
     "name": "Vineyard Wind / Revolution",
     "geo": "US East Coast",
     "cur": "US$",
     "ebitda": 278,
     "ev": 3500,
     "entry": 12.5,
     "exit": 10.5,
     "lev": 5,
     "growth": 2,
     "hold": 14,
     "rd": 6.5,
     "uirr": "6.8%",
     "lirr": "7.6%",
     "moic": "2.33×"
    },
    {
     "key": "brazil",
     "name": "Brazil offshore wind",
     "geo": "Brazil (NE coast)",
     "cur": "R$",
     "ebitda": 1030,
     "ev": 13500,
     "entry": 13,
     "exit": 9,
     "lev": 5,
     "growth": 4,
     "hold": 14,
     "rd": 11,
     "uirr": "6.8%",
     "lirr": "6.6%",
     "moic": "2.22×"
    },
    {
     "key": "starsouth",
     "name": "Star of the South",
     "geo": "Bass Strait, Australia",
     "cur": "A$",
     "ebitda": 487,
     "ev": 5600,
     "entry": 11.5,
     "exit": 10.5,
     "lev": 5,
     "growth": 2,
     "hold": 14,
     "rd": 7,
     "uirr": "7.4%",
     "lirr": "8.5%",
     "moic": "2.60×"
    },
    {
     "key": "changhua",
     "name": "Greater Changhua",
     "geo": "Taiwan Strait",
     "cur": "US$",
     "ebitda": 313,
     "ev": 4000,
     "entry": 13,
     "exit": 10.5,
     "lev": 6,
     "growth": 1.5,
     "hold": 14,
     "rd": 5.5,
     "uirr": "6.6%",
     "lirr": "7.8%",
     "moic": "2.36×"
    },
    {
     "key": "china",
     "name": "China offshore wind",
     "geo": "China east coast",
     "cur": "$",
     "ebitda": 1390,
     "ev": 17000,
     "entry": 12,
     "exit": 10,
     "lev": 6,
     "growth": 1.5,
     "hold": 15,
     "rd": 4,
     "uirr": "6.5%",
     "lirr": "8.6%",
     "moic": "2.65×"
    }
   ]
  },
  {
   "cls": "Energy Transition",
   "name": "Solar",
   "url": "solar.html",
   "assets": [
    {
     "key": "iberia",
     "name": "Iberian solar",
     "geo": "Spain",
     "cur": "€",
     "ebitda": 19.8,
     "ev": 255,
     "entry": 13,
     "exit": 11,
     "lev": 5,
     "growth": 1.5,
     "hold": 25,
     "rd": 5,
     "uirr": "7.0%",
     "lirr": "8.1%",
     "moic": "3.82×"
    },
    {
     "key": "ussolar",
     "name": "US utility-scale solar",
     "geo": "Texas / California, USA",
     "cur": "US$",
     "ebitda": 21.2,
     "ev": 315,
     "entry": 15,
     "exit": 11,
     "lev": 5,
     "growth": 2,
     "hold": 25,
     "rd": 5.5,
     "uirr": "6.7%",
     "lirr": "7.3%",
     "moic": "3.49×"
    },
    {
     "key": "atacama",
     "name": "Atacama solar",
     "geo": "Atacama Desert, Chile",
     "cur": "US$",
     "ebitda": 17.6,
     "ev": 205,
     "entry": 11.5,
     "exit": 10,
     "lev": 4,
     "growth": 1.5,
     "hold": 22,
     "rd": 8.5,
     "uirr": "7.4%",
     "lirr": "7.7%",
     "moic": "3.23×"
    },
    {
     "key": "ausolar",
     "name": "Australian solar farm",
     "geo": "Australia (NEM)",
     "cur": "A$",
     "ebitda": 15.2,
     "ev": 184,
     "entry": 12,
     "exit": 9,
     "lev": 4,
     "growth": 1,
     "hold": 22,
     "rd": 6.5,
     "uirr": "6.1%",
     "lirr": "6.6%",
     "moic": "2.64×"
    },
    {
     "key": "aldhafra",
     "name": "Al Dhafra / Sweihan solar",
     "geo": "Abu Dhabi, UAE",
     "cur": "$",
     "ebitda": 64.5,
     "ev": 984,
     "entry": 15.5,
     "exit": 9,
     "lev": 6,
     "growth": 1,
     "hold": 28,
     "rd": 4,
     "uirr": "6.8%",
     "lirr": "8.0%",
     "moic": "3.62×"
    },
    {
     "key": "chinapv",
     "name": "Chinese desert mega-base",
     "geo": "Gobi / NW China",
     "cur": "$",
     "ebitda": 937,
     "ev": 12000,
     "entry": 13,
     "exit": 8,
     "lev": 5,
     "growth": 1,
     "hold": 25,
     "rd": 4,
     "uirr": "6.0%",
     "lirr": "7.3%",
     "moic": "3.06×"
    }
   ]
  },
  {
   "cls": "Energy Transition",
   "name": "Battery storage",
   "url": "battery-storage.html",
   "assets": [
    {
     "key": "gbbess",
     "name": "GB grid-scale battery",
     "geo": "Great Britain",
     "cur": "£",
     "ebitda": 12.4,
     "ev": 95,
     "entry": 7.5,
     "exit": 9,
     "lev": 3,
     "growth": 1,
     "hold": 12,
     "rd": 6,
     "uirr": "10.7%",
     "lirr": "13.3%",
     "moic": "3.09×"
    },
    {
     "key": "ercot",
     "name": "ERCOT / CAISO battery",
     "geo": "Texas / California, USA",
     "cur": "US$",
     "ebitda": 15.8,
     "ev": 108,
     "entry": 7,
     "exit": 8,
     "lev": 2.5,
     "growth": 0,
     "hold": 10,
     "rd": 7,
     "uirr": "11.0%",
     "lirr": "13.4%",
     "moic": "2.62×"
    },
    {
     "key": "chile",
     "name": "Chilean solar-paired battery",
     "geo": "Atacama, Chile",
     "cur": "US$",
     "ebitda": 10.5,
     "ev": 111,
     "entry": 10.5,
     "exit": 9,
     "lev": 5,
     "growth": 2,
     "hold": 14,
     "rd": 8.5,
     "uirr": "7.5%",
     "lirr": "8.4%",
     "moic": "2.51×"
    },
    {
     "key": "australia",
     "name": "Victorian Big Battery / Hornsdale",
     "geo": "Victoria / South Australia",
     "cur": "A$",
     "ebitda": 18.6,
     "ev": 160,
     "entry": 8.5,
     "exit": 9,
     "lev": 4,
     "growth": 1,
     "hold": 13,
     "rd": 6.5,
     "uirr": "8.6%",
     "lirr": "10.8%",
     "moic": "2.85×"
    },
    {
     "key": "gulf",
     "name": "Saudi / UAE utility battery",
     "geo": "Saudi Arabia / UAE",
     "cur": "$",
     "ebitda": 19.9,
     "ev": 230,
     "entry": 11.5,
     "exit": 10,
     "lev": 6,
     "growth": 1,
     "hold": 15,
     "rd": 5,
     "uirr": "8.5%",
     "lirr": "11.2%",
     "moic": "3.05×"
    },
    {
     "key": "china",
     "name": "Chinese grid-scale battery",
     "geo": "China (national)",
     "cur": "$",
     "ebitda": 24.6,
     "ev": 250,
     "entry": 10,
     "exit": 8,
     "lev": 5,
     "growth": 1,
     "hold": 12,
     "rd": 4,
     "uirr": "6.5%",
     "lirr": "9.0%",
     "moic": "2.20×"
    }
   ]
  },
  {
   "cls": "Energy Transition",
   "name": "Hydrogen",
   "url": "hydrogen.html",
   "assets": [
    {
     "key": "euroh2",
     "name": "European electrolyser",
     "geo": "Germany / Netherlands",
     "cur": "€",
     "ebitda": 28.4,
     "ev": 300,
     "entry": 10.5,
     "exit": 10,
     "lev": 4,
     "growth": 2,
     "hold": 20,
     "rd": 5.5,
     "uirr": "6.8%",
     "lirr": "7.8%",
     "moic": "3.15×"
    },
    {
     "key": "gulfh2",
     "name": "US Gulf Coast green H2",
     "geo": "Texas / Louisiana, USA",
     "cur": "US$",
     "ebitda": 50.6,
     "ev": 580,
     "entry": 11.5,
     "exit": 10,
     "lev": 4.5,
     "growth": 2,
     "hold": 20,
     "rd": 6,
     "uirr": "6.5%",
     "lirr": "7.4%",
     "moic": "2.98×"
    },
    {
     "key": "atacama",
     "name": "HIF / Atacama green H2",
     "geo": "Atacama, Chile",
     "cur": "US$",
     "ebitda": 85.3,
     "ev": 920,
     "entry": 11,
     "exit": 10,
     "lev": 4,
     "growth": 3,
     "hold": 20,
     "rd": 7,
     "uirr": "8.1%",
     "lirr": "9.2%",
     "moic": "3.83×"
    },
    {
     "key": "murchison",
     "name": "Murchison / CWP green H2",
     "geo": "Western Australia",
     "cur": "A$",
     "ebitda": 192,
     "ev": 2055,
     "entry": 10.5,
     "exit": 10,
     "lev": 4.5,
     "growth": 3,
     "hold": 20,
     "rd": 6.5,
     "uirr": "7.8%",
     "lirr": "9.3%",
     "moic": "3.94×"
    },
    {
     "key": "neom",
     "name": "NEOM Green Hydrogen",
     "geo": "NEOM, Saudi Arabia",
     "cur": "$",
     "ebitda": 269,
     "ev": 4200,
     "entry": 15.5,
     "exit": 10,
     "lev": 4.5,
     "growth": 3,
     "hold": 22,
     "rd": 5.5,
     "uirr": "7.3%",
     "lirr": "7.8%",
     "moic": "3.19×"
    },
    {
     "key": "chinah2",
     "name": "Chinese green hydrogen",
     "geo": "Inner Mongolia / NW China",
     "cur": "$",
     "ebitda": 157,
     "ev": 2038,
     "entry": 13,
     "exit": 9,
     "lev": 4.5,
     "growth": 3,
     "hold": 22,
     "rd": 4,
     "uirr": "6.8%",
     "lirr": "8.2%",
     "moic": "3.44×"
    }
   ]
  },
  {
   "cls": "Energy Transition",
   "name": "Nuclear",
   "url": "nuclear.html",
   "assets": [
    {
     "key": "hinkley",
     "name": "Hinkley Point C",
     "geo": "Somerset, United Kingdom",
     "cur": "£",
     "ebitda": 2373,
     "ev": 29000,
     "entry": 12,
     "exit": 12,
     "lev": 4,
     "growth": 2,
     "hold": 20,
     "rd": 5,
     "uirr": "7.8%",
     "lirr": "9.0%",
     "moic": "3.52×"
    },
    {
     "key": "vogtle",
     "name": "Vogtle 3 & 4",
     "geo": "Georgia, USA",
     "cur": "US$",
     "ebitda": 1340,
     "ev": 16500,
     "entry": 12.5,
     "exit": 12,
     "lev": 4,
     "growth": 2,
     "hold": 20,
     "rd": 5.25,
     "uirr": "7.7%",
     "lirr": "8.9%",
     "moic": "3.46×"
    },
    {
     "key": "angra",
     "name": "Angra (Eletronuclear)",
     "geo": "Angra dos Reis, Brazil",
     "cur": "R$",
     "ebitda": 4661,
     "ev": 57000,
     "entry": 12,
     "exit": 10,
     "lev": 3.5,
     "growth": 3,
     "hold": 20,
     "rd": 11,
     "uirr": "7.5%",
     "lirr": "7.6%",
     "moic": "3.15×"
    },
    {
     "key": "barakah",
     "name": "Barakah",
     "geo": "Al Dhafra, United Arab Emirates",
     "cur": "$",
     "ebitda": 5219,
     "ev": 73000,
     "entry": 14,
     "exit": 12,
     "lev": 4,
     "growth": 2,
     "hold": 20,
     "rd": 4.75,
     "uirr": "8.4%",
     "lirr": "9.4%",
     "moic": "3.40×"
    },
    {
     "key": "cgn",
     "name": "CGN (China nuclear)",
     "geo": "Coastal China",
     "cur": "$",
     "ebitda": 4801,
     "ev": 60000,
     "entry": 12.5,
     "exit": 11,
     "lev": 3.5,
     "growth": 2,
     "hold": 20,
     "rd": 3.5,
     "uirr": "7.4%",
     "lirr": "8.5%",
     "moic": "3.19×"
    },
    {
     "key": "smr",
     "name": "Small modular reactor (SMR)",
     "geo": "Global (illustrative)",
     "cur": "£",
     "ebitda": 275,
     "ev": 3403,
     "entry": 12.5,
     "exit": 11,
     "lev": 3.5,
     "growth": 2,
     "hold": 20,
     "rd": 6,
     "uirr": "7.4%",
     "lirr": "8.2%",
     "moic": "3.13×"
    }
   ]
  },
  {
   "cls": "Energy Transition",
   "name": "Pumped hydro",
   "url": "pumped-hydro.html",
   "assets": [
    {
     "key": "coireglas",
     "name": "Coire Glas / Cruachan",
     "geo": "Scottish Highlands, UK",
     "cur": "£",
     "ebitda": 136,
     "ev": 1648,
     "entry": 12,
     "exit": 12,
     "lev": 3,
     "growth": 1,
     "hold": 25,
     "rd": 5.5,
     "uirr": "7.1%",
     "lirr": "7.7%",
     "moic": "3.41×"
    },
    {
     "key": "bathcounty",
     "name": "Bath County",
     "geo": "Virginia, USA (PJM)",
     "cur": "US$",
     "ebitda": 376,
     "ev": 4900,
     "entry": 13,
     "exit": 11,
     "lev": 4,
     "growth": 1,
     "hold": 25,
     "rd": 6.5,
     "uirr": "6.3%",
     "lirr": "6.7%",
     "moic": "3.05×"
    },
    {
     "key": "espejo",
     "name": "Espejo de Tarapacá",
     "geo": "Atacama, Chile",
     "cur": "US$",
     "ebitda": 39.6,
     "ev": 620,
     "entry": 15.5,
     "exit": 11,
     "lev": 4,
     "growth": 2,
     "hold": 26,
     "rd": 8.5,
     "uirr": "5.8%",
     "lirr": "5.7%",
     "moic": "2.92×"
    },
    {
     "key": "snowy",
     "name": "Snowy 2.0",
     "geo": "Snowy Mountains, NSW, Australia",
     "cur": "A$",
     "ebitda": 290,
     "ev": 4100,
     "entry": 14,
     "exit": 12,
     "lev": 3,
     "growth": 1,
     "hold": 30,
     "rd": 5.5,
     "uirr": "5.6%",
     "lirr": "5.9%",
     "moic": "3.15×"
    },
    {
     "key": "hatta",
     "name": "Hatta",
     "geo": "Hatta, Dubai, UAE",
     "cur": "$",
     "ebitda": 31.4,
     "ev": 540,
     "entry": 17,
     "exit": 11,
     "lev": 5,
     "growth": 1,
     "hold": 28,
     "rd": 5,
     "uirr": "6.0%",
     "lirr": "6.3%",
     "moic": "3.00×"
    },
    {
     "key": "fengning",
     "name": "Fengning",
     "geo": "Hebei, China",
     "cur": "$",
     "ebitda": 429,
     "ev": 6100,
     "entry": 14,
     "exit": 11,
     "lev": 4,
     "growth": 1,
     "hold": 28,
     "rd": 4,
     "uirr": "5.8%",
     "lirr": "6.4%",
     "moic": "3.15×"
    }
   ]
  },
  {
   "cls": "Environmental & Waste",
   "name": "Waste-to-energy",
   "url": "waste-to-energy.html",
   "assets": [
    {
     "key": "ukefw",
     "name": "UK / European energy-from-waste",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 37.8,
     "ev": 380,
     "entry": 10,
     "exit": 10,
     "lev": 5,
     "growth": 2.5,
     "hold": 15,
     "rd": 5,
     "uirr": "8.4%",
     "lirr": "11.4%",
     "moic": "3.48×"
    },
    {
     "key": "covanta",
     "name": "Covanta",
     "geo": "United States",
     "cur": "US$",
     "ebitda": 26,
     "ev": 265,
     "entry": 10,
     "exit": 10,
     "lev": 5,
     "growth": 2.5,
     "hold": 15,
     "rd": 5.5,
     "uirr": "8.1%",
     "lirr": "10.6%",
     "moic": "3.28×"
    },
    {
     "key": "brazilwte",
     "name": "Brazilian / Latin American WtE",
     "geo": "Brazil",
     "cur": "R$",
     "ebitda": 29.5,
     "ev": 270,
     "entry": 9,
     "exit": 9,
     "lev": 4,
     "growth": 4,
     "hold": 14,
     "rd": 9,
     "uirr": "9.1%",
     "lirr": "10.7%",
     "moic": "3.33×"
    },
    {
     "key": "kwinana",
     "name": "Kwinana / Avertas Energy",
     "geo": "Western Australia",
     "cur": "A$",
     "ebitda": 27.9,
     "ev": 277,
     "entry": 10,
     "exit": 10,
     "lev": 5,
     "growth": 2.5,
     "hold": 15,
     "rd": 6,
     "uirr": "7.8%",
     "lirr": "10.2%",
     "moic": "3.25×"
    },
    {
     "key": "warsan",
     "name": "Warsan waste-to-energy (Dubai)",
     "geo": "Dubai, UAE",
     "cur": "$",
     "ebitda": 441,
     "ev": 4450,
     "entry": 10,
     "exit": 10,
     "lev": 6,
     "growth": 2.5,
     "hold": 11,
     "rd": 5,
     "uirr": "10.8%",
     "lirr": "16.8%",
     "moic": "3.56×"
    },
    {
     "key": "chinawte",
     "name": "China Everbright-style WtE",
     "geo": "China",
     "cur": "$",
     "ebitda": 70.7,
     "ev": 700,
     "entry": 10,
     "exit": 10,
     "lev": 5,
     "growth": 3,
     "hold": 13,
     "rd": 4,
     "uirr": "8.9%",
     "lirr": "12.9%",
     "moic": "3.42×"
    }
   ]
  },
  {
   "cls": "Environmental & Waste",
   "name": "Anaerobic digestion",
   "url": "anaerobic-digestion.html",
   "assets": [
    {
     "key": "ukbio",
     "name": "UK biomethane-to-grid",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 5.8,
     "ev": 50,
     "entry": 8.5,
     "exit": 9.5,
     "lev": 4,
     "growth": 2,
     "hold": 14,
     "rd": 6,
     "uirr": "9.1%",
     "lirr": "11.5%",
     "moic": "3.43×"
    },
    {
     "key": "usrng",
     "name": "US renewable natural gas (RNG)",
     "geo": "United States",
     "cur": "US$",
     "ebitda": 6.5,
     "ev": 57,
     "entry": 9,
     "exit": 9.5,
     "lev": 4,
     "growth": 3,
     "hold": 13,
     "rd": 6.5,
     "uirr": "10.0%",
     "lirr": "12.5%",
     "moic": "3.53×"
    },
    {
     "key": "brbio",
     "name": "Brazilian agri-biogas",
     "geo": "Brazil",
     "cur": "R$",
     "ebitda": 3.6,
     "ev": 34,
     "entry": 9.5,
     "exit": 9,
     "lev": 4,
     "growth": 4,
     "hold": 14,
     "rd": 9,
     "uirr": "9.4%",
     "lirr": "10.6%",
     "moic": "3.41×"
    },
    {
     "key": "ausfw",
     "name": "Australian food-waste AD",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 3.1,
     "ev": 30,
     "entry": 9.5,
     "exit": 9.5,
     "lev": 4,
     "growth": 3.5,
     "hold": 15,
     "rd": 6.5,
     "uirr": "8.8%",
     "lirr": "10.4%",
     "moic": "3.47×"
    },
    {
     "key": "gulffw",
     "name": "Gulf food-waste AD",
     "geo": "Gulf / GCC",
     "cur": "$",
     "ebitda": 2.6,
     "ev": 27,
     "entry": 10.5,
     "exit": 9.5,
     "lev": 4,
     "growth": 4,
     "hold": 14,
     "rd": 7,
     "uirr": "10.3%",
     "lirr": "11.7%",
     "moic": "3.48×"
    },
    {
     "key": "cnbio",
     "name": "Chinese large-scale biogas",
     "geo": "China",
     "cur": "$",
     "ebitda": 6.5,
     "ev": 72,
     "entry": 11,
     "exit": 9,
     "lev": 5,
     "growth": 4,
     "hold": 16,
     "rd": 4.5,
     "uirr": "8.0%",
     "lirr": "10.0%",
     "moic": "3.55×"
    }
   ]
  },
  {
   "cls": "Environmental & Waste",
   "name": "Recycling infrastructure",
   "url": "recycling-infrastructure.html",
   "assets": [
    {
     "key": "ukmrf",
     "name": "UK materials recovery facility",
     "geo": "United Kingdom",
     "cur": "£",
     "ebitda": 4.8,
     "ev": 36,
     "entry": 7.5,
     "exit": 8.5,
     "lev": 4,
     "growth": 2,
     "hold": 12,
     "rd": 6,
     "uirr": "9.3%",
     "lirr": "12.7%",
     "moic": "3.27×"
    },
    {
     "key": "usmrf",
     "name": "US single-stream MRF",
     "geo": "United States",
     "cur": "US$",
     "ebitda": 8.6,
     "ev": 70,
     "entry": 8,
     "exit": 8.5,
     "lev": 4,
     "growth": 3,
     "hold": 12,
     "rd": 6.5,
     "uirr": "9.7%",
     "lirr": "12.6%",
     "moic": "3.25×"
    },
    {
     "key": "brmrf",
     "name": "Brazilian recycling plant",
     "geo": "Brazil",
     "cur": "R$",
     "ebitda": 8.6,
     "ev": 64,
     "entry": 7.5,
     "exit": 8,
     "lev": 3,
     "growth": 4,
     "hold": 12,
     "rd": 13,
     "uirr": "9.4%",
     "lirr": "9.7%",
     "moic": "2.82×"
    },
    {
     "key": "aumrf",
     "name": "Australian MRF",
     "geo": "Australia",
     "cur": "A$",
     "ebitda": 5.6,
     "ev": 43,
     "entry": 7.5,
     "exit": 8.5,
     "lev": 4,
     "growth": 2,
     "hold": 13,
     "rd": 6,
     "uirr": "9.0%",
     "lirr": "12.2%",
     "moic": "3.37×"
    },
    {
     "key": "beeah",
     "name": "Bee'ah material recovery facility",
     "geo": "Sharjah, UAE",
     "cur": "$",
     "ebitda": 18.8,
     "ev": 150,
     "entry": 8,
     "exit": 7,
     "lev": 4,
     "growth": 2,
     "hold": 12,
     "rd": 5,
     "uirr": "11.0%",
     "lirr": "15.4%",
     "moic": "3.28×"
    },
    {
     "key": "cnmrf",
     "name": "Chinese recycling plant",
     "geo": "China",
     "cur": "$",
     "ebitda": 83.7,
     "ev": 580,
     "entry": 7,
     "exit": 6,
     "lev": 4,
     "growth": 2,
     "hold": 13,
     "rd": 4,
     "uirr": "9.0%",
     "lirr": "14.6%",
     "moic": "3.49×"
    }
   ]
  }
 ]
};
