/* Landmark infrastructure M&A deals, shared dataset.
   Used by both the M&A module (infrastructure-ma.html) and the standalone deals
   database (infrastructure-deals.html). Figures are at announcement, as reported
   (a mix of enterprise and equity value), rounded; sources are listed on the
   deals page. Each `url` links to the most relevant sub-sector reference page. */
window.MA_DEALS = [
  /* t: target, a: acquirer, y: year, cls: asset class, region, type, val: value text,
     usd: approx US$bn for sorting, why: one-liner, url: reference page */
  {t:'Thames Water', a:'Macquarie-led consortium', y:2006, cls:'Energy & Utilities', region:'UK', type:'Carve-out', val:'EV £8.5bn', usd:15.0, why:'UK water utility bought from RWE; c.£6.5bn RAB. The archetypal regulated-utility buyout, and a cautionary tale on leverage.', url:'water-wastewater.html'},
  {t:'BAA (Heathrow + UK airports)', a:'Ferrovial-led consortium (GIC, CDPQ)', y:2006, cls:'Transport', region:'UK', type:'Take-private', val:'£10.3bn equity', usd:19.0, why:"One of Europe's largest LBOs; took a listed UK airports group private under majority foreign ownership.", url:'airports.html'},
  {t:'P&O Ports', a:'DP World', y:2006, cls:'Transport', region:'UK / Global', type:'Take-private', val:'£3.9bn', usd:6.8, why:"State-owned operator buys the world's #4 ports group; US terminals later divested after political backlash, classic FDI/political risk.", url:'ports.html'},
  {t:'Gatwick Airport', a:'Global Infrastructure Partners', y:2009, cls:'Transport', region:'UK', type:'Carve-out', val:'£1.51bn', usd:2.5, why:"BAA forced to divest by the UK competition authority; GIP's carve-out became a model infra-fund single-asset deal.", url:'airports.html'},
  {t:'UK Power Networks', a:'CKI / HK Electric (Li Ka-shing)', y:2010, cls:'Energy & Utilities', region:'UK', type:'Carve-out', val:'£5.78bn', usd:9.1, why:'Three UK electricity distribution networks bought from EDF; a long-hold strategic acquirer of regulated grids.', url:'electricity-distribution.html'},
  {t:'DUET Group', a:'CKI / Li Ka-shing consortium', y:2017, cls:'Energy & Utilities', region:'Australia', type:'Take-private', val:'A$7.4bn', usd:5.5, why:'Listed Australian gas & electricity networks taken private, energy distribution as a long-hold regulated asset.', url:'gas-distribution.html'},
  {t:'Nat. Grid Gas Distribution (Cadent)', a:'Macquarie-led consortium (Allianz, QIA, CIC)', y:2017, cls:'Energy & Utilities', region:'UK', type:'Carve-out', val:'EV £13.8bn', usd:17.5, why:"61% of the UK's largest gas distribution network carved out of National Grid; consortium of infra managers and sovereign funds.", url:'gas-distribution.html'},
  {t:'Abertis', a:'Atlantia + ACS / Hochtief', y:2018, cls:'Transport', region:'Europe', type:'Take-private', val:'€16.5bn', usd:19.0, why:"Created the world's largest toll-road group; a contested takeover battle resolved by a joint bid.", url:'roads.html'},
  {t:'Buckeye Partners', a:'IFM Investors', y:2019, cls:'Energy & Utilities', region:'North America', type:'Take-private', val:'EV $10.3bn', usd:10.3, why:'Take-private of a US midstream pipeline & storage network by a pension-backed infra manager.', url:'gas-transmission.html'},
  {t:'CK Hutchison European towers', a:'Cellnex', y:2020, cls:'Digital Infrastructure', region:'Europe', type:'Carve-out', val:'€10bn', usd:11.8, why:'24,600 towers across six countries; the towerco roll-up model, buy passive infrastructure, lease to multiple operators.', url:'mobile-towers.html'},
  {t:'Inter Pipeline', a:'Brookfield Infrastructure', y:2021, cls:'Energy & Utilities', region:'North America', type:'Take-private', val:'C$16.50 / sh', usd:13.5, why:'Canadian midstream platform taken private after a contested bid, a buyer converting a stake into full control.', url:'gas-transmission.html'},
  {t:'CyrusOne', a:'KKR + Global Infrastructure Partners', y:2021, cls:'Digital Infrastructure', region:'North America', type:'Take-private', val:'$15bn', usd:15.0, why:'Take-private of a data-centre REIT; digital infrastructure firmly inside the infra-fund mandate.', url:'data-centres.html'},
  {t:'CoreSite', a:'American Tower', y:2021, cls:'Digital Infrastructure', region:'North America', type:'Take-private', val:'$10.1bn', usd:10.1, why:'A towerco buys an interconnection-rich data-centre platform, convergence of wireless and wireline infrastructure.', url:'data-centres.html'},
  {t:'QTS Realty', a:'Blackstone', y:2021, cls:'Digital Infrastructure', region:'North America', type:'Take-private', val:'$10bn', usd:10.0, why:'Then the largest-ever data-centre take-private; perpetual-capital vehicles buying hyperscale capacity.', url:'data-centres.html'},
  {t:'Telxius Towers', a:'American Tower', y:2021, cls:'Digital Infrastructure', region:'Europe / LatAm', type:'Carve-out', val:'€7.7bn', usd:9.4, why:'~31,000 towers carved out of Telefónica at record multiples, the great European tower consolidation.', url:'mobile-towers.html'},
  {t:'Aramco Oil Pipelines (49%)', a:'EIG-led consortium', y:2021, cls:'Energy & Utilities', region:'Middle East', type:'Lease / minority stake', val:'$12.4bn', usd:12.4, why:'A 25-year lease-and-leaseback over crude pipelines sold to investors, monetising a national champion via an infrastructure stake.', url:'gas-transmission.html'},
  {t:'Aramco Gas Pipelines (49%)', a:'BlackRock / Hassana consortium', y:2021, cls:'Energy & Utilities', region:'Middle East', type:'Lease / minority stake', val:'$15.5bn', usd:15.5, why:'A 20-year gas-pipeline lease stake; sovereign-scale infrastructure opened to global institutional capital.', url:'gas-transmission.html'},
  {t:'Sydney Airport', a:'Sydney Aviation Alliance (IFM, AustralianSuper, ART, GIP)', y:2022, cls:'Transport', region:'Australia', type:'Take-private', val:'A$23.6bn equity', usd:17.0, why:"Australia's largest take-private; domestic pension capital and infra funds buying a monopoly gateway airport at a full price.", url:'airports.html'},
  {t:'ContourGlobal', a:'KKR', y:2022, cls:'Energy Transition', region:'Global', type:'Take-private', val:'£1.75bn', usd:2.2, why:'Take-private of a listed global power producer (thermal + renewables) to accelerate its energy-transition build-out.', url:'onshore-wind.html'},
  {t:'Vantage Towers', a:'KKR + GIP consortium (with Vodafone)', y:2022, cls:'Digital Infrastructure', region:'Europe', type:'Carve-out / JV', val:'EV €16bn', usd:16.0, why:'Co-control partnership over Vodafone’s European towers, a strategic releasing capital into a dedicated infra JV.', url:'mobile-towers.html'},
  {t:'Telecom Italia NetCo', a:'KKR-led consortium (ADIA, CPPIB, F2i)', y:2024, cls:'Digital Infrastructure', region:'Europe', type:'Carve-out', val:'EV up to €22bn', usd:23.6, why:"Europe's largest-ever carve-out of a national fixed telecoms network into a stand-alone infrastructure asset.", url:'fibre-networks.html'},
  {t:'Global Infrastructure Partners', a:'BlackRock', y:2024, cls:'Platform / GP', region:'Global', type:'GP / platform M&A', val:'$12.5bn', usd:12.5, why:'The asset manager buys the largest independent infra GP, consolidation at the platform level, not the asset level.', url:''},
  {t:'Neoen', a:'Brookfield + co-investors', y:2024, cls:'Energy Transition', region:'Europe', type:'Take-private', val:'€6.1bn', usd:6.6, why:'Take-private of a French renewables and battery-storage developer; scaling a clean-energy platform across markets.', url:'solar.html'},
  {t:'CK Hutchison ports portfolio', a:'BlackRock / TiL (MSC) consortium', y:2025, cls:'Transport', region:'Global', type:'Carve-out', val:'EV $22.8bn', usd:22.8, why:'80% of 43 global ports incl. Panama Canal terminals; agreed 2025, then contested in Panama, geopolitics meets infrastructure.', url:'ports.html'}
];
